{"uid":"e05e18936cba287e","name":"test_fetch_community_with_latency","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_latency","historyId":"b219078e02c2b2383da3ebd6787c88d5","time":{"start":1725409954340,"stop":1725410029055,"duration":74715},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:34: in test_fetch_community_with_latency\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1725408678813,"stop":1725408678814,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1725409946528,"stop":1725409946528,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1725409946529,"stop":1725409954340,"duration":7811},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1725409946529,"stop":1725409946529,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:34: in test_fetch_community_with_latency\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=35252): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"f34ec83f3aacfb9f","name":"log","source":"f34ec83f3aacfb9f.txt","type":"text/plain","size":237790}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1725410029338,"stop":1725410029341,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1725410029341,"stop":1725410029538,"duration":197},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1725411368056,"stop":1725411368056,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az774-457"},{"name":"thread","value":"10230-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":32,"skipped":0,"passed":23,"unknown":0,"total":56},"items":[{"uid":"29b3ad8712ab3d6f","reportUrl":"https://status-im.github.io/status-cli-tests/188//#testresult/29b3ad8712ab3d6f","status":"passed","time":{"start":1725323547803,"stop":1725323609276,"duration":61473}},{"uid":"ac04de6e550b38de","reportUrl":"https://status-im.github.io/status-cli-tests/187//#testresult/ac04de6e550b38de","status":"passed","time":{"start":1725237105235,"stop":1725237159335,"duration":54100}},{"uid":"adc6f0ab915d6705","reportUrl":"https://status-im.github.io/status-cli-tests/186//#testresult/adc6f0ab915d6705","status":"passed","time":{"start":1725150970257,"stop":1725151032360,"duration":62103}},{"uid":"6a20fd06a753afe7","reportUrl":"https://status-im.github.io/status-cli-tests/185//#testresult/6a20fd06a753afe7","status":"passed","time":{"start":1725064540467,"stop":1725064591416,"duration":50949}},{"uid":"2bf6d76f8d344012","reportUrl":"https://status-im.github.io/status-cli-tests/184//#testresult/2bf6d76f8d344012","status":"passed","time":{"start":1724978104326,"stop":1724978158708,"duration":54382}},{"uid":"2f86eb9efc1ec422","reportUrl":"https://status-im.github.io/status-cli-tests/183//#testresult/2f86eb9efc1ec422","status":"passed","time":{"start":1724891793188,"stop":1724891846655,"duration":53467}},{"uid":"254a745c78f15129","reportUrl":"https://status-im.github.io/status-cli-tests/182//#testresult/254a745c78f15129","status":"passed","time":{"start":1724805462880,"stop":1724805514935,"duration":52055}},{"uid":"77e85e8f275ba1a6","reportUrl":"https://status-im.github.io/status-cli-tests/181//#testresult/77e85e8f275ba1a6","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=57387): Read timed out. (read timeout=10)","time":{"start":1724719052501,"stop":1724719157812,"duration":105311}},{"uid":"783f480fc8228c7e","reportUrl":"https://status-im.github.io/status-cli-tests/180//#testresult/783f480fc8228c7e","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=50903): Read timed out. (read timeout=10)","time":{"start":1724632785886,"stop":1724632860592,"duration":74706}},{"uid":"f8ebbc1d93491db1","reportUrl":"https://status-im.github.io/status-cli-tests/179//#testresult/f8ebbc1d93491db1","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=21246): Read timed out. (read timeout=10)","time":{"start":1724546331887,"stop":1724546386376,"duration":54489}},{"uid":"ea790cd7b23c8614","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/ea790cd7b23c8614","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=55608): Read timed out. (read timeout=10)","time":{"start":1724459737011,"stop":1724459791497,"duration":54486}},{"uid":"2e24c19d323dbd6","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/2e24c19d323dbd6","status":"passed","time":{"start":1724373308664,"stop":1724373364680,"duration":56016}},{"uid":"a7c0d21a524cc14a","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/a7c0d21a524cc14a","status":"passed","time":{"start":1724286843356,"stop":1724286922342,"duration":78986}},{"uid":"c9b68442e74442f5","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/c9b68442e74442f5","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=13073): Read timed out. (read timeout=10)","time":{"start":1724256811847,"stop":1724256866350,"duration":54503}},{"uid":"766bfdfa08b2c666","reportUrl":"https://status-im.github.io/status-cli-tests/174//#testresult/766bfdfa08b2c666","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x025c6a4061775152f076c00af2ae78308c4aa35b3e9c497b8d781925617a83ec6c, Error: 'NoneType' object is not subscriptable","time":{"start":1724242088656,"stop":1724242158485,"duration":69829}},{"uid":"de2b1b7198dbc694","reportUrl":"https://status-im.github.io/status-cli-tests/173//#testresult/de2b1b7198dbc694","status":"passed","time":{"start":1724236630999,"stop":1724236689330,"duration":58331}},{"uid":"7d52c60e189d4e88","reportUrl":"https://status-im.github.io/status-cli-tests/172//#testresult/7d52c60e189d4e88","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=43123): Read timed out. (read timeout=2)","time":{"start":1724200479588,"stop":1724200542827,"duration":63239}},{"uid":"223cba5d1a4ace54","reportUrl":"https://status-im.github.io/status-cli-tests/171//#testresult/223cba5d1a4ace54","status":"passed","time":{"start":1724161464641,"stop":1724161528920,"duration":64279}},{"uid":"5f22435ccd07ae62","reportUrl":"https://status-im.github.io/status-cli-tests/170//#testresult/5f22435ccd07ae62","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=13784): Read timed out. (read timeout=2)","time":{"start":1724157105787,"stop":1724157151015,"duration":45228}},{"uid":"c2fe3657d1c20b5b","reportUrl":"https://status-im.github.io/status-cli-tests/168//#testresult/c2fe3657d1c20b5b","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=40706): Read timed out. (read timeout=2)","time":{"start":1724113821934,"stop":1724113867161,"duration":45227}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"e05e18936cba287e.json","parameterValues":[]}