{"uid":"63ff3a62771edc4a","name":"test_fetch_community_with_packet_loss","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_packet_loss","historyId":"0eca0edbd90df8c1e44c54fb8592b7c8","time":{"start":1726532872170,"stop":1726532958808,"duration":86638},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:10690 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=10690): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=10690): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:40: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:20: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:10690 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1726531812729,"stop":1726531812729,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1726532864358,"stop":1726532872170,"duration":7812},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1726532864358,"stop":1726532864358,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1726532864358,"stop":1726532864358,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:10690 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=10690): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=10690): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:40: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:20: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:10690 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"b28f8aaff9aa8a78","name":"log","source":"b28f8aaff9aa8a78.txt","type":"text/plain","size":87840}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1726532959101,"stop":1726532959104,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1726532959104,"stop":1726532959239,"duration":135},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1726533875841,"stop":1726533875842,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1019-803"},{"name":"thread","value":"10345-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":7,"broken":48,"skipped":0,"passed":16,"unknown":0,"total":71},"items":[{"uid":"551f32b1d74a5946","reportUrl":"https://status-im.github.io/status-cli-tests/203//#testresult/551f32b1d74a5946","status":"failed","statusDetails":"AssertionError: 4 community fetches out of 10: ,Community ID: 0x032af744fdcabe073e24fddeb5b9127abe6a94e844ce9b9f2763ec21fc2e078f00, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03aee94ee001c222c94c22b8274d9f9de61f1f697fe9b353c94a7c4bad14bb1755, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x034940a94a265ba008eda880deeac73bfbb5a128fac9c5ffc35452cc205f856df1, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02d425f2e3bfc7cd72078dc314edf857781eb0c2b8ef8ad60c093059b31f4d5695, Error: 'NoneType' object is not subscriptable","time":{"start":1726446492865,"stop":1726446584549,"duration":91684}},{"uid":"efc07fd1077deff5","reportUrl":"https://status-im.github.io/status-cli-tests/202//#testresult/efc07fd1077deff5","status":"failed","statusDetails":"AssertionError: 9 community fetches out of 10: ,Community ID: 0x032af744fdcabe073e24fddeb5b9127abe6a94e844ce9b9f2763ec21fc2e078f00, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03aee94ee001c222c94c22b8274d9f9de61f1f697fe9b353c94a7c4bad14bb1755, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x034940a94a265ba008eda880deeac73bfbb5a128fac9c5ffc35452cc205f856df1, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x0361558ace12880d6a7201725507aa64a8a9a1cc7d30a3c1e9daae69ef11129fc6, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02d425f2e3bfc7cd72078dc314edf857781eb0c2b8ef8ad60c093059b31f4d5695, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02ddaa8aaaddcc0fa106e5f80ec851b669563f4c3be42a3ad362c3ae204e5175bd, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x0286ac005d0ffaacb5bdfd72df2b6a745c166892ec4cc6b0f9584421c8b1b0756c, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x035b7fb2f8928696264bdbef3c863dfb5f86f24e0117ea5393ab32d298b4e619a3, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x038bf0d1e9e0ec492310b84c1ef5e13ac893ca7f11d0b9c0162d087a19235355e0, Error: 'NoneType' object is not subscriptable","time":{"start":1726360122759,"stop":1726360167534,"duration":44775}},{"uid":"ec6fedfd1e9bd6ac","reportUrl":"https://status-im.github.io/status-cli-tests/201//#testresult/ec6fedfd1e9bd6ac","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x032af744fdcabe073e24fddeb5b9127abe6a94e844ce9b9f2763ec21fc2e078f00, Error: 'NoneType' object is not subscriptable","time":{"start":1726273613489,"stop":1726273721476,"duration":107987}},{"uid":"334673470eccd8e3","reportUrl":"https://status-im.github.io/status-cli-tests/200//#testresult/334673470eccd8e3","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62249 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1726187261838,"stop":1726187318713,"duration":56875}},{"uid":"8f83eea581691377","reportUrl":"https://status-im.github.io/status-cli-tests/199//#testresult/8f83eea581691377","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:5793 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1726100893511,"stop":1726100972969,"duration":79458}},{"uid":"73be887be0434140","reportUrl":"https://status-im.github.io/status-cli-tests/198//#testresult/73be887be0434140","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:9026 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1726067536606,"stop":1726067591108,"duration":54502}},{"uid":"f7ba565dfd44f73","reportUrl":"https://status-im.github.io/status-cli-tests/197//#testresult/f7ba565dfd44f73","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62854 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1726050186660,"stop":1726050271599,"duration":84939}},{"uid":"2a9ddf349713a9cf","reportUrl":"https://status-im.github.io/status-cli-tests/196//#testresult/2a9ddf349713a9cf","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=2577): Read timed out. (read timeout=10)","time":{"start":1726014849872,"stop":1726014948960,"duration":99088}},{"uid":"a5980bb702c33543","reportUrl":"https://status-im.github.io/status-cli-tests/195//#testresult/a5980bb702c33543","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=16066): Read timed out. (read timeout=10)","time":{"start":1725928548524,"stop":1725928637502,"duration":88978}},{"uid":"fe38cf1bbacb5ce5","reportUrl":"https://status-im.github.io/status-cli-tests/194//#testresult/fe38cf1bbacb5ce5","status":"passed","time":{"start":1725842009605,"stop":1725842086518,"duration":76913}},{"uid":"dc0d4ead0e0dc352","reportUrl":"https://status-im.github.io/status-cli-tests/193//#testresult/dc0d4ead0e0dc352","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=39206): Read timed out. (read timeout=10)","time":{"start":1725755816742,"stop":1725755878553,"duration":61811}},{"uid":"f870d5ab7af8e7e2","reportUrl":"https://status-im.github.io/status-cli-tests/192//#testresult/f870d5ab7af8e7e2","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=21370): Read timed out. (read timeout=10)","time":{"start":1725669301069,"stop":1725669355559,"duration":54490}},{"uid":"cf48064f76abc4d3","reportUrl":"https://status-im.github.io/status-cli-tests/191//#testresult/cf48064f76abc4d3","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=40187): Read timed out. (read timeout=10)","time":{"start":1725582919397,"stop":1725582973889,"duration":54492}},{"uid":"49ec9cc7f24b1f76","reportUrl":"https://status-im.github.io/status-cli-tests/190//#testresult/49ec9cc7f24b1f76","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=62906): Read timed out. (read timeout=10)","time":{"start":1725496606349,"stop":1725496660865,"duration":54516}},{"uid":"5204944cb47fd1d","reportUrl":"https://status-im.github.io/status-cli-tests/189//#testresult/5204944cb47fd1d","status":"passed","time":{"start":1725410037352,"stop":1725410082287,"duration":44935}},{"uid":"6cfd90dbb04ab784","reportUrl":"https://status-im.github.io/status-cli-tests/188//#testresult/6cfd90dbb04ab784","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=62508): Read timed out. (read timeout=10)","time":{"start":1725323617192,"stop":1725323676442,"duration":59250}},{"uid":"8cc2968b4925ce85","reportUrl":"https://status-im.github.io/status-cli-tests/187//#testresult/8cc2968b4925ce85","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=37122): Read timed out. (read timeout=10)","time":{"start":1725237167304,"stop":1725237224736,"duration":57432}},{"uid":"354b27f498b2d24b","reportUrl":"https://status-im.github.io/status-cli-tests/186//#testresult/354b27f498b2d24b","status":"passed","time":{"start":1725151040313,"stop":1725151089547,"duration":49234}},{"uid":"7d2cd00a1f4751a0","reportUrl":"https://status-im.github.io/status-cli-tests/185//#testresult/7d2cd00a1f4751a0","status":"passed","time":{"start":1725064599483,"stop":1725064646884,"duration":47401}},{"uid":"1358c2a7e93cb82e","reportUrl":"https://status-im.github.io/status-cli-tests/184//#testresult/1358c2a7e93cb82e","status":"passed","time":{"start":1724978166629,"stop":1724978216986,"duration":50357}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"63ff3a62771edc4a.json","parameterValues":[]}