{"uid":"b24b050aaecfaddb","name":"test_join_community_with_latency","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_latency","historyId":"c03b8c5d33abbf92b5cd45f8a8de165b","time":{"start":1721893409096,"stop":1721893501998,"duration":92902},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)","statusTrace":"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/socket.py:708: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:58: in test_join_community_with_latency\n    self.test_join_community_baseline()\ntests/test_join_community.py:20: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:169: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=2)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)","flaky":true,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1721891830411,"stop":1721891830411,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1721893401386,"stop":1721893409096,"duration":7710},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1721893401386,"stop":1721893401386,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1721893401386,"stop":1721893401386,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)","statusTrace":"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/socket.py:708: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:58: in test_join_community_with_latency\n    self.test_join_community_baseline()\ntests/test_join_community.py:20: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:169: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=2)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=19262): Read timed out. (read timeout=2)","steps":[],"attachments":[{"uid":"129be47ad5013531","name":"log","source":"129be47ad5013531.txt","type":"text/plain","size":74159}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1721893502206,"stop":1721893502208,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1721893502209,"stop":1721893502387,"duration":178},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1721894546465,"stop":1721894546466,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az774-46"},{"name":"thread","value":"10241-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":5,"skipped":0,"passed":2,"unknown":0,"total":9},"items":[{"uid":"6b01a6beaa85f82b","reportUrl":"https://status-im.github.io/status-cli-tests/140//#testresult/6b01a6beaa85f82b","status":"passed","time":{"start":1721888831492,"stop":1721888905522,"duration":74030}},{"uid":"3be79552288e3c0f","reportUrl":"https://status-im.github.io/status-cli-tests/139//#testresult/3be79552288e3c0f","status":"failed","statusDetails":"AssertionError: 9 community joins out of 10: Join Timestamp: 00:31:31, Accept Timestamp: 00:32:13,Community ID: 0x02d55cbc3b9e8b8304f8d977abfc61947a3e68b0e005ecefacef8ec797595679fa, Error: 'result'\nJoin Timestamp: 00:31:35, Accept Timestamp: 00:32:13,Community ID: 0x0279581caee768abf28dfb4a6ac83b1a177d3c7131c21625b503958b6586a0cf72, Error: 'result'\nJoin Timestamp: 00:31:39, Accept Timestamp: 00:32:13,Community ID: 0x032fce8f4f7cd4ca6cced3ec374671648977db3c91e3532afa1c0877a36ff3d230, Error: 'result'\nJoin Timestamp: 00:31:46, Accept Timestamp: 00:32:13,Community ID: 0x028fddc25502249fc5b82dadef9a7ab4fc91b87177e573f8954ac5c79ffd73eefb, Error: 'result'\nJoin Timestamp: 00:31:49, Accept Timestamp: 00:32:13,Community ID: 0x034f0eeec0661d63cf79a765363406489798fa680013e3f268e206f2cc39d21308, Error: 'result'\nJoin Timestamp: 00:31:52, Accept Timestamp: 00:32:13,Community ID: 0x029e7b6e358bf8948693e4369673f1efa5a464d4ac21c5d183cb1c902b1cf644fc, Error: 'result'\nJoin Timestamp: 00:31:56, Accept Timestamp: 00:32:13,Community ID: 0x0304d7a831170c96a778fe078d558245f52db2f32ab9629a5a3b5f22f6dfc4625a, Error: 'result'\nJoin Timestamp: 00:32:01, Accept Timestamp: 00:32:13,Community ID: 0x02a016c6e808d9fda950fb19c2c31946dbd0af77bd28946b514a398e2eba218504, Error: 'result'\nJoin Timestamp: 00:32:04, Accept Timestamp: 00:32:13,Community ID: 0x036398afb89fd22f8b191d436447aa12a6cf8714f698a07a02ca53118ee50064eb, Error: 'result'","time":{"start":1721867471815,"stop":1721867533988,"duration":62173}},{"uid":"6ff90d57d98c7043","reportUrl":"https://status-im.github.io/status-cli-tests/138//#testresult/6ff90d57d98c7043","status":"passed","time":{"start":1721847491001,"stop":1721847545505,"duration":54504}},{"uid":"2724b747c2a90280","reportUrl":"https://status-im.github.io/status-cli-tests/137//#testresult/2724b747c2a90280","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=57104): Read timed out. (read timeout=10)","time":{"start":1721841389338,"stop":1721841419528,"duration":30190}},{"uid":"e42e569474f16f4a","reportUrl":"https://status-im.github.io/status-cli-tests/136//#testresult/e42e569474f16f4a","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61462): Read timed out. (read timeout=10)","time":{"start":1721828291040,"stop":1721828321169,"duration":30129}},{"uid":"c10dec3ad39ddd60","reportUrl":"https://status-im.github.io/status-cli-tests/135//#testresult/c10dec3ad39ddd60","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=43892): Read timed out. (read timeout=10)","time":{"start":1721823642715,"stop":1721823672875,"duration":30160}},{"uid":"39cb6a1d516d7d7c","reportUrl":"https://status-im.github.io/status-cli-tests/134//#testresult/39cb6a1d516d7d7c","status":"failed","statusDetails":"AssertionError: 4 community joins out of 10: Join Timestamp: 12:09:18, Accept Timestamp: 12:09:57,Community ID: 0x029e7b6e358bf8948693e4369673f1efa5a464d4ac21c5d183cb1c902b1cf644fc, Error: 'result'\nJoin Timestamp: 12:09:29, Accept Timestamp: 12:09:57,Community ID: 0x028fddc25502249fc5b82dadef9a7ab4fc91b87177e573f8954ac5c79ffd73eefb, Error: 'result'\nJoin Timestamp: 12:09:38, Accept Timestamp: 12:09:57,Community ID: 0x02a016c6e808d9fda950fb19c2c31946dbd0af77bd28946b514a398e2eba218504, Error: 'result'\nJoin Timestamp: 12:09:45, Accept Timestamp: 12:09:57,Community ID: 0x02d55cbc3b9e8b8304f8d977abfc61947a3e68b0e005ecefacef8ec797595679fa, Error: 'result'","time":{"start":1721822938249,"stop":1721822997269,"duration":59020}},{"uid":"7bf52a735846f633","reportUrl":"https://status-im.github.io/status-cli-tests/133//#testresult/7bf52a735846f633","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=54636): Read timed out. (read timeout=10)","time":{"start":1721818942890,"stop":1721818973063,"duration":30173}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"b24b050aaecfaddb.json","parameterValues":[]}