{"uid":"5cc0b8ef9415f996","name":"test_join_community_with_packet_loss","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_packet_loss","historyId":"447b5e60edf20b9d6546c17e4d82b687","time":{"start":1730767106740,"stop":1730767176515,"duration":69775},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:36112 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=36112): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=36112): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:36112 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1730765772530,"stop":1730765772530,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1730767098928,"stop":1730767098928,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1730767098928,"stop":1730767098928,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1730767098929,"stop":1730767106740,"duration":7811},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:36112 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=36112): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=36112): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:36112 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"ed5749a8d98d7b6a","name":"log","source":"ed5749a8d98d7b6a.txt","type":"text/plain","size":76307}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1730767176731,"stop":1730767176733,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1730767176734,"stop":1730767176985,"duration":251},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1730767802266,"stop":1730767802266,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az1532-499"},{"name":"thread","value":"60793-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":12,"broken":12,"skipped":0,"passed":3,"unknown":0,"total":27},"items":[{"uid":"3e8d7cc6d8388d13","reportUrl":"https://status-im.github.io/status-cli-tests/264//#testresult/3e8d7cc6d8388d13","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730680550028,"stop":1730680631115,"duration":81087}},{"uid":"b21240c52bc986b5","reportUrl":"https://status-im.github.io/status-cli-tests/263//#testresult/b21240c52bc986b5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:3899 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730594469480,"stop":1730594526377,"duration":56897}},{"uid":"eb7ce259443aae16","reportUrl":"https://status-im.github.io/status-cli-tests/262//#testresult/eb7ce259443aae16","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:47087 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730508180474,"stop":1730508269207,"duration":88733}},{"uid":"b9bc60df0e82846e","reportUrl":"https://status-im.github.io/status-cli-tests/261//#testresult/b9bc60df0e82846e","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730421741420,"stop":1730421822674,"duration":81254}},{"uid":"c228beb9213b3b5c","reportUrl":"https://status-im.github.io/status-cli-tests/260//#testresult/c228beb9213b3b5c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730335170121,"stop":1730335240944,"duration":70823}},{"uid":"eec2a9c24540a657","reportUrl":"https://status-im.github.io/status-cli-tests/259//#testresult/eec2a9c24540a657","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:13915 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730248782086,"stop":1730248856846,"duration":74760}},{"uid":"631fb36c8ffc07f3","reportUrl":"https://status-im.github.io/status-cli-tests/258//#testresult/631fb36c8ffc07f3","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730162235288,"stop":1730162334552,"duration":99264}},{"uid":"53d1b6d0a5b25854","reportUrl":"https://status-im.github.io/status-cli-tests/257//#testresult/53d1b6d0a5b25854","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:17811 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730075740909,"stop":1730075839431,"duration":98522}},{"uid":"b8b1783f35751df6","reportUrl":"https://status-im.github.io/status-cli-tests/256//#testresult/b8b1783f35751df6","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729989394394,"stop":1729989468092,"duration":73698}},{"uid":"1283e96e9f28e05f","reportUrl":"https://status-im.github.io/status-cli-tests/255//#testresult/1283e96e9f28e05f","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:36458 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729902984233,"stop":1729903041484,"duration":57251}},{"uid":"bf7bb696d963b739","reportUrl":"https://status-im.github.io/status-cli-tests/254//#testresult/bf7bb696d963b739","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:43175 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729816563279,"stop":1729816700267,"duration":136988}},{"uid":"393bef68cf02a3a","reportUrl":"https://status-im.github.io/status-cli-tests/253//#testresult/393bef68cf02a3a","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:44057 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729730219542,"stop":1729730274985,"duration":55443}},{"uid":"329e2556284575cd","reportUrl":"https://status-im.github.io/status-cli-tests/252//#testresult/329e2556284575cd","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729643701964,"stop":1729643765137,"duration":63173}},{"uid":"2d6117ec146be8e","reportUrl":"https://status-im.github.io/status-cli-tests/251//#testresult/2d6117ec146be8e","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729557382301,"stop":1729557439629,"duration":57328}},{"uid":"3c151a7bd1d70605","reportUrl":"https://status-im.github.io/status-cli-tests/250//#testresult/3c151a7bd1d70605","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:55072 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729470935802,"stop":1729471007585,"duration":71783}},{"uid":"872d9456248fdad5","reportUrl":"https://status-im.github.io/status-cli-tests/249//#testresult/872d9456248fdad5","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729384566687,"stop":1729384678505,"duration":111818}},{"uid":"ba0ef0f52d196c11","reportUrl":"https://status-im.github.io/status-cli-tests/248//#testresult/ba0ef0f52d196c11","status":"passed","time":{"start":1729297972423,"stop":1729298056606,"duration":84183}},{"uid":"efef9630983e58e9","reportUrl":"https://status-im.github.io/status-cli-tests/247//#testresult/efef9630983e58e9","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729211747201,"stop":1729211833147,"duration":85946}},{"uid":"fc6e31efd90b23a3","reportUrl":"https://status-im.github.io/status-cli-tests/246//#testresult/fc6e31efd90b23a3","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:42353 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729125246729,"stop":1729125313286,"duration":66557}},{"uid":"c9b5ae864c67881c","reportUrl":"https://status-im.github.io/status-cli-tests/245//#testresult/c9b5ae864c67881c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:56031 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1729068226789,"stop":1729068281749,"duration":54960}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"5cc0b8ef9415f996.json","parameterValues":[]}