{"uid":"fc8fd561b56e3bd1","name":"test_join_community_with_latency","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_latency","historyId":"c03b8c5d33abbf92b5cd45f8a8de165b","time":{"start":1736987296014,"stop":1736987359468,"duration":63454},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:42339 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=42339): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42339): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:55: in test_join_community_with_latency\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:42339 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":true,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1736986554338,"stop":1736986554338,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1736987288205,"stop":1736987288205,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1736987288205,"stop":1736987288205,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1736987288206,"stop":1736987296014,"duration":7808},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:42339 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=42339): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42339): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:55: in test_join_community_with_latency\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:42339 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"64b0bac19229719b","name":"log","source":"64b0bac19229719b.txt","type":"text/plain","size":102236}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1736987359742,"stop":1736987359744,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1736987359745,"stop":1736987359860,"duration":115},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1736987850604,"stop":1736987850604,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az1758-2"},{"name":"thread","value":"60405-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":31,"broken":58,"skipped":0,"passed":11,"unknown":0,"total":100},"items":[{"uid":"29ee7f35db3ff067","reportUrl":"https://status-im.github.io/status-cli-tests/338//#testresult/29ee7f35db3ff067","status":"passed","time":{"start":1736900886375,"stop":1736900944172,"duration":57797}},{"uid":"d5bb209066e7b7f5","reportUrl":"https://status-im.github.io/status-cli-tests/336//#testresult/d5bb209066e7b7f5","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1736728107535,"stop":1736728175174,"duration":67639}},{"uid":"f9b570fffa6cc647","reportUrl":"https://status-im.github.io/status-cli-tests/335//#testresult/f9b570fffa6cc647","status":"passed","time":{"start":1736641765821,"stop":1736641823491,"duration":57670}},{"uid":"f0f969cfe2fd9885","reportUrl":"https://status-im.github.io/status-cli-tests/334//#testresult/f0f969cfe2fd9885","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1736555281927,"stop":1736555347562,"duration":65635}},{"uid":"bd3607ab696333a","reportUrl":"https://status-im.github.io/status-cli-tests/333//#testresult/bd3607ab696333a","status":"passed","time":{"start":1736468917830,"stop":1736468972960,"duration":55130}},{"uid":"4aa5fd889dfb7744","reportUrl":"https://status-im.github.io/status-cli-tests/332//#testresult/4aa5fd889dfb7744","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1736382549066,"stop":1736382614950,"duration":65884}},{"uid":"3eb95e5331f25b62","reportUrl":"https://status-im.github.io/status-cli-tests/331//#testresult/3eb95e5331f25b62","status":"passed","time":{"start":1736320344320,"stop":1736320401926,"duration":57606}},{"uid":"f54b46fc5c902909","reportUrl":"https://status-im.github.io/status-cli-tests/330//#testresult/f54b46fc5c902909","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:12821 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736317063599,"stop":1736317118034,"duration":54435}},{"uid":"a823c8f1ed78dc16","reportUrl":"https://status-im.github.io/status-cli-tests/329//#testresult/a823c8f1ed78dc16","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:59722 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736296583555,"stop":1736296644107,"duration":60552}},{"uid":"98e9f642204a82c9","reportUrl":"https://status-im.github.io/status-cli-tests/328//#testresult/98e9f642204a82c9","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:22582 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736210379408,"stop":1736210439679,"duration":60271}},{"uid":"adcab20fa5b0dec4","reportUrl":"https://status-im.github.io/status-cli-tests/327//#testresult/adcab20fa5b0dec4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:15441 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736123890038,"stop":1736123946818,"duration":56780}},{"uid":"1141c01c36e2c15c","reportUrl":"https://status-im.github.io/status-cli-tests/326//#testresult/1141c01c36e2c15c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62135 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1736037589631,"stop":1736037646723,"duration":57092}},{"uid":"93642fbbebf60f72","reportUrl":"https://status-im.github.io/status-cli-tests/325//#testresult/93642fbbebf60f72","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62487 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735951060060,"stop":1735951117054,"duration":56994}},{"uid":"cce2fca19994534a","reportUrl":"https://status-im.github.io/status-cli-tests/324//#testresult/cce2fca19994534a","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:16943 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735864611009,"stop":1735864669085,"duration":58076}},{"uid":"fd8540c1cba05650","reportUrl":"https://status-im.github.io/status-cli-tests/323//#testresult/fd8540c1cba05650","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:8647 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735778171230,"stop":1735778228306,"duration":57076}},{"uid":"5f24400edcec17ed","reportUrl":"https://status-im.github.io/status-cli-tests/322//#testresult/5f24400edcec17ed","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:22968 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735691905829,"stop":1735691962890,"duration":57061}},{"uid":"54359e192ce598ea","reportUrl":"https://status-im.github.io/status-cli-tests/321//#testresult/54359e192ce598ea","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:36316 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735605414819,"stop":1735605472019,"duration":57200}},{"uid":"4cfa286e91c9a1b","reportUrl":"https://status-im.github.io/status-cli-tests/320//#testresult/4cfa286e91c9a1b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:31113 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735519042337,"stop":1735519099258,"duration":56921}},{"uid":"b0ec070064b798d8","reportUrl":"https://status-im.github.io/status-cli-tests/319//#testresult/b0ec070064b798d8","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:19132 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735432688783,"stop":1735432745886,"duration":57103}},{"uid":"3668c0c348e0d8e4","reportUrl":"https://status-im.github.io/status-cli-tests/318//#testresult/3668c0c348e0d8e4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:34019 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1735346281714,"stop":1735346339525,"duration":57811}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"fc8fd561b56e3bd1.json","parameterValues":[]}