{"uid":"d84e6093ba59a8d0","name":"test_leave_community_with_latency","fullName":"tests.test_leave_community.TestLeaveCommunity#test_leave_community_with_latency","historyId":"79f7e4ee5aacb6424b78fe6ee6a94dab","time":{"start":1724546934234,"stop":1724546988725,"duration":54491},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:40: in test_leave_community_with_latency\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)","flaky":true,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1724544684688,"stop":1724544684688,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1724546926524,"stop":1724546926525,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1724546926525,"stop":1724546926525,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1724546926525,"stop":1724546934234,"duration":7709},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:40: in test_leave_community_with_latency\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"d6459a1b4d5418f3","name":"log","source":"d6459a1b4d5418f3.txt","type":"text/plain","size":127450}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1724546988939,"stop":1724546988942,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1724546988942,"stop":1724546989163,"duration":221},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1724547849042,"stop":1724547849042,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_leave_community"},{"name":"subSuite","value":"TestLeaveCommunity"},{"name":"host","value":"fv-az1432-853"},{"name":"thread","value":"10205-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_leave_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":27,"broken":8,"skipped":0,"passed":11,"unknown":0,"total":46},"items":[{"uid":"9668c0c21489c3b8","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/9668c0c21489c3b8","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8730): Read timed out. (read timeout=10)","time":{"start":1724460592980,"stop":1724460647476,"duration":54496}},{"uid":"767679ff854770c6","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/767679ff854770c6","status":"passed","time":{"start":1724373821655,"stop":1724373869289,"duration":47634}},{"uid":"1e4eff22fd49d505","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/1e4eff22fd49d505","status":"passed","time":{"start":1724287325475,"stop":1724287373177,"duration":47702}},{"uid":"a5cd17c4a8b05f79","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/a5cd17c4a8b05f79","status":"failed","statusDetails":"AssertionError","time":{"start":1724257363388,"stop":1724257423077,"duration":59689}},{"uid":"2f35d3247d135cee","reportUrl":"https://status-im.github.io/status-cli-tests/174//#testresult/2f35d3247d135cee","status":"passed","time":{"start":1724242627923,"stop":1724242675679,"duration":47756}},{"uid":"90233522ede81edd","reportUrl":"https://status-im.github.io/status-cli-tests/173//#testresult/90233522ede81edd","status":"passed","time":{"start":1724237108147,"stop":1724237166880,"duration":58733}},{"uid":"70a5f77c5e92e6d5","reportUrl":"https://status-im.github.io/status-cli-tests/172//#testresult/70a5f77c5e92e6d5","status":"failed","statusDetails":"AssertionError: 1 community joins out of 10: Leave Timestamp: 00:43:12, Community ID: 0x03b35a6ea06115c3d362f232062545e530d7d41dc80392bb7bf5e87b3eb1be0f68, Error: Comunity doesn't have the initial number of members after join and leave, so leave probably failed\nassert 18 == 1\n +  where 18 = len({'0x040e2759e05ceee3542780ab42f4008052b149990320813c1f7175d95ae1aee12b01b7df67245fb345fcd711648558d9c54011fb0afea619fc4a9cb5ee15b29c8b': {'last_update_clock': 1724161842}, '0x041fcbc4449ced2f4205597d1fb0f4506b44e0659f98cc56ea4e3b5b1d4cb026401c3ea5f7695f2f18fa5b9f76e150a11ec1429f02c59f2959da04244dfc7cd317': {'last_update_clock': 1724161657}, '0x042ba411422281182b3e52c2314e9895c1a0920b2119074e3e1ce57ff4ad15835855d6f4de777e10bd7b4cfe33497e2e1d9f951164330cc82c65561ad8fa44ff64': {'last_update_clock': 1724200846}, '0x042d180a162e6ecac0ce9ea7e0c2814777312cfe77b6ea588166b1a038fa5cc6382a31879f1e5ae8c789029d984be5c97ac7124a7ffe8a585cd636921e36f969b4': {'last_update_clock': 1724161979}, ...})","time":{"start":1724200944667,"stop":1724200992377,"duration":47710}},{"uid":"554b3a6ed7bc3ca2","reportUrl":"https://status-im.github.io/status-cli-tests/171//#testresult/554b3a6ed7bc3ca2","status":"failed","statusDetails":"AssertionError: 2 community joins out of 10: Leave Timestamp: 13:53:22, Community ID: 0x035183f4ddcf985762f43d91089b874bb5797446e8d1fe01c3d63251a3922cb1f6, Error: Comunity doesn't have the initial number of members after join and leave, so leave probably failed\nassert 1 == 6\n +  where 1 = len({'0x04486492d3806dce55a29f37698877a01f37186a6181fbfb3b662bd66e0dd2ccf2e73af273b50efc30b7d20594d07b0859d66a947176483e3fa9d51a7627ef395f': {'roles': [1]}})\nLeave Timestamp: 13:53:22, Community ID: 0x021e2785163d8e3c323915d127cd60e16035b9ec7399395711e0919900948455e5, Error: Comunity doesn't have the initial number of members after join and leave, so leave probably failed\nassert 1 == 7\n +  where 1 = len({'0x04797c0ca5573f1b9ab73246fa9f655a53617bc41b23ba12bc0348effa6fd604ee59aef3dc8c09f850a56c231affaa56bf03abd489254a9ce0f792178840ea28bf': {'roles': [1]}})","time":{"start":1724161953281,"stop":1724162002065,"duration":48784}},{"uid":"17d167314b983073","reportUrl":"https://status-im.github.io/status-cli-tests/170//#testresult/17d167314b983073","status":"failed","statusDetails":"AssertionError","time":{"start":1724157509342,"stop":1724157544185,"duration":34843}},{"uid":"9587830f28e2ba88","reportUrl":"https://status-im.github.io/status-cli-tests/168//#testresult/9587830f28e2ba88","status":"failed","statusDetails":"AssertionError","time":{"start":1724114222908,"stop":1724114257527,"duration":34619}},{"uid":"a0f979b77d96d56a","reportUrl":"https://status-im.github.io/status-cli-tests/167//#testresult/a0f979b77d96d56a","status":"failed","statusDetails":"AssertionError","time":{"start":1724027839636,"stop":1724027874230,"duration":34594}},{"uid":"565854aac9131ff8","reportUrl":"https://status-im.github.io/status-cli-tests/166//#testresult/565854aac9131ff8","status":"failed","statusDetails":"AssertionError","time":{"start":1723941517387,"stop":1723941551897,"duration":34510}},{"uid":"a8592574dd9fc14e","reportUrl":"https://status-im.github.io/status-cli-tests/165//#testresult/a8592574dd9fc14e","status":"failed","statusDetails":"AssertionError","time":{"start":1723855035356,"stop":1723855070078,"duration":34722}},{"uid":"e7cc461c94f155c2","reportUrl":"https://status-im.github.io/status-cli-tests/164//#testresult/e7cc461c94f155c2","status":"failed","statusDetails":"AssertionError","time":{"start":1723768684716,"stop":1723768722285,"duration":37569}},{"uid":"a44e303853ce6993","reportUrl":"https://status-im.github.io/status-cli-tests/163//#testresult/a44e303853ce6993","status":"failed","statusDetails":"AssertionError","time":{"start":1723682229650,"stop":1723682264209,"duration":34559}},{"uid":"3ed313818d1b2fde","reportUrl":"https://status-im.github.io/status-cli-tests/162//#testresult/3ed313818d1b2fde","status":"failed","statusDetails":"AssertionError","time":{"start":1723595809181,"stop":1723595843796,"duration":34615}},{"uid":"e3eecc7f339b8079","reportUrl":"https://status-im.github.io/status-cli-tests/161//#testresult/e3eecc7f339b8079","status":"failed","statusDetails":"AssertionError","time":{"start":1723509466767,"stop":1723509513697,"duration":46930}},{"uid":"51d5142e77e5f6b0","reportUrl":"https://status-im.github.io/status-cli-tests/160//#testresult/51d5142e77e5f6b0","status":"failed","statusDetails":"AssertionError","time":{"start":1723422968983,"stop":1723423003572,"duration":34589}},{"uid":"a13f89a2ec9ed0c7","reportUrl":"https://status-im.github.io/status-cli-tests/159//#testresult/a13f89a2ec9ed0c7","status":"failed","statusDetails":"AssertionError","time":{"start":1723336798593,"stop":1723336833243,"duration":34650}},{"uid":"f2c8cac44e4872b5","reportUrl":"https://status-im.github.io/status-cli-tests/158//#testresult/f2c8cac44e4872b5","status":"failed","statusDetails":"AssertionError","time":{"start":1723250274338,"stop":1723250309120,"duration":34782}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"d84e6093ba59a8d0.json","parameterValues":[]}