{"uid":"4e2785b2d5c7a6aa","name":"test_leave_community_baseline","fullName":"tests.test_leave_community.TestLeaveCommunity#test_leave_community_baseline","historyId":"ba5f179862c2394ab88a56b56e94ab6d","time":{"start":1733878310320,"stop":1733878436265,"duration":125945},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:1821 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=1821): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=1821): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:13: in test_leave_community_baseline\n    self.join_created_communities()\nsrc/steps/common.py:175: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:1821 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":2,"retriesStatusChange":true,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1733876225067,"stop":1733876225067,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1733878302507,"stop":1733878302507,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1733878302508,"stop":1733878302508,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1733878302508,"stop":1733878310319,"duration":7811},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:1821 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=1821): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=1821): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:13: in test_leave_community_baseline\n    self.join_created_communities()\nsrc/steps/common.py:175: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:1821 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"c32d35ad3c7ec6c2","name":"log","source":"c32d35ad3c7ec6c2.txt","type":"text/plain","size":793627}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1733878436479,"stop":1733878436481,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1733878436482,"stop":1733878436681,"duration":199},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1733878727292,"stop":1733878727293,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"flaky(reruns=2)"},{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_leave_community"},{"name":"subSuite","value":"TestLeaveCommunity"},{"name":"host","value":"fv-az1043-896"},{"name":"thread","value":"60587-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_leave_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"ea1a7f93156df763","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733878222418,"stop":1733878302272,"duration":79854}},{"uid":"1289c22ccdae4ec2","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733878123645,"stop":1733878214367,"duration":90722}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":50,"broken":4,"skipped":0,"passed":9,"unknown":0,"total":63},"items":[{"uid":"2cf66d7f2bcb0975","reportUrl":"https://status-im.github.io/status-cli-tests/300//#testresult/2cf66d7f2bcb0975","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733791211819,"stop":1733791261405,"duration":49586}},{"uid":"6cda1f9806569825","reportUrl":"https://status-im.github.io/status-cli-tests/299//#testresult/6cda1f9806569825","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733704788071,"stop":1733704831523,"duration":43452}},{"uid":"87107ba238ac1a2e","reportUrl":"https://status-im.github.io/status-cli-tests/298//#testresult/87107ba238ac1a2e","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733618711376,"stop":1733618769569,"duration":58193}},{"uid":"bef1615bb21088f4","reportUrl":"https://status-im.github.io/status-cli-tests/297//#testresult/bef1615bb21088f4","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733532362113,"stop":1733532429250,"duration":67137}},{"uid":"a7d517f2f6d5686d","reportUrl":"https://status-im.github.io/status-cli-tests/296//#testresult/a7d517f2f6d5686d","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733446330229,"stop":1733446404780,"duration":74551}},{"uid":"11ceee790d1db5d2","reportUrl":"https://status-im.github.io/status-cli-tests/295//#testresult/11ceee790d1db5d2","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733359934042,"stop":1733360012269,"duration":78227}},{"uid":"f24e110835a7d0a7","reportUrl":"https://status-im.github.io/status-cli-tests/294//#testresult/f24e110835a7d0a7","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733273580786,"stop":1733273648948,"duration":68162}},{"uid":"590c84d798f1711c","reportUrl":"https://status-im.github.io/status-cli-tests/293//#testresult/590c84d798f1711c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733186959786,"stop":1733187027495,"duration":67709}},{"uid":"c33cd545d6f224dd","reportUrl":"https://status-im.github.io/status-cli-tests/292//#testresult/c33cd545d6f224dd","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733100493889,"stop":1733100560631,"duration":66742}},{"uid":"f21da89b5da5cdb","reportUrl":"https://status-im.github.io/status-cli-tests/291//#testresult/f21da89b5da5cdb","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1733014357299,"stop":1733014423687,"duration":66388}},{"uid":"3629e87e7829a230","reportUrl":"https://status-im.github.io/status-cli-tests/290//#testresult/3629e87e7829a230","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732927813848,"stop":1732927880379,"duration":66531}},{"uid":"aa1432243bd902ff","reportUrl":"https://status-im.github.io/status-cli-tests/289//#testresult/aa1432243bd902ff","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732841363957,"stop":1732841430188,"duration":66231}},{"uid":"dc9373d5416547c6","reportUrl":"https://status-im.github.io/status-cli-tests/288//#testresult/dc9373d5416547c6","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732755067192,"stop":1732755132186,"duration":64994}},{"uid":"700aaecb889c5ce2","reportUrl":"https://status-im.github.io/status-cli-tests/287//#testresult/700aaecb889c5ce2","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:61565 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1732668515694,"stop":1732668614709,"duration":99015}},{"uid":"e654b549addfe253","reportUrl":"https://status-im.github.io/status-cli-tests/286//#testresult/e654b549addfe253","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732582101880,"stop":1732582163758,"duration":61878}},{"uid":"15fd6f6aed788f67","reportUrl":"https://status-im.github.io/status-cli-tests/285//#testresult/15fd6f6aed788f67","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732495465863,"stop":1732495525069,"duration":59206}},{"uid":"9be45ffbd0fbe3a4","reportUrl":"https://status-im.github.io/status-cli-tests/284//#testresult/9be45ffbd0fbe3a4","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732409022018,"stop":1732409070741,"duration":48723}},{"uid":"39b15bf767c9f913","reportUrl":"https://status-im.github.io/status-cli-tests/283//#testresult/39b15bf767c9f913","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732322477554,"stop":1732322534650,"duration":57096}},{"uid":"bd40dbc04b696fe0","reportUrl":"https://status-im.github.io/status-cli-tests/282//#testresult/bd40dbc04b696fe0","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732236438981,"stop":1732236488938,"duration":49957}},{"uid":"bb346f1968261a7c","reportUrl":"https://status-im.github.io/status-cli-tests/281//#testresult/bb346f1968261a7c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1732149870159,"stop":1732149916339,"duration":46180}}]},"tags":["@pytest.mark.usefixtures('start_1_node')","flaky(reruns=2)"]},"source":"4e2785b2d5c7a6aa.json","parameterValues":[]}