{"uid":"95bf815e9de23ad4","name":"test_community_messages_with_node_pause_10_seconds","fullName":"tests.test_community_messages.TestCommunityMessages#test_community_messages_with_node_pause_10_seconds","historyId":"9d5c5c19a9c20059f4a5d5c182032b2c","time":{"start":1723767177917,"stop":1723767204916,"duration":26999},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)","statusTrace":"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/socket.py:708: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_community_messages.py:72: in test_community_messages_with_node_pause_10_seconds\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=2)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1723767039135,"stop":1723767039135,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1723767170105,"stop":1723767170105,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1723767170105,"stop":1723767170105,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1723767170105,"stop":1723767177917,"duration":7812},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)","statusTrace":"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/socket.py:708: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_community_messages.py:72: in test_community_messages_with_node_pause_10_seconds\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=2)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11695): Read timed out. (read timeout=2)","steps":[],"attachments":[{"uid":"ed24f62f4dea6dbe","name":"log","source":"ed24f62f4dea6dbe.txt","type":"text/plain","size":9872}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1723767205121,"stop":1723767205122,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1723767205122,"stop":1723767205141,"duration":19},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1723769554401,"stop":1723769554401,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_community_messages"},{"name":"subSuite","value":"TestCommunityMessages"},{"name":"host","value":"fv-az532-375"},{"name":"thread","value":"10245-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_community_messages"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":10,"broken":2,"skipped":0,"passed":19,"unknown":0,"total":31},"items":[{"uid":"b9477ded2e81a64","reportUrl":"https://status-im.github.io/status-cli-tests/163//#testresult/b9477ded2e81a64","status":"failed","statusDetails":"AssertionError","time":{"start":1723680744619,"stop":1723680760894,"duration":16275}},{"uid":"fbab89b42ed4af22","reportUrl":"https://status-im.github.io/status-cli-tests/162//#testresult/fbab89b42ed4af22","status":"failed","statusDetails":"AssertionError","time":{"start":1723594346453,"stop":1723594362846,"duration":16393}},{"uid":"88385dbb1e9c3588","reportUrl":"https://status-im.github.io/status-cli-tests/161//#testresult/88385dbb1e9c3588","status":"failed","statusDetails":"AssertionError","time":{"start":1723507945249,"stop":1723507963045,"duration":17796}},{"uid":"c1f74b61b3ddb374","reportUrl":"https://status-im.github.io/status-cli-tests/160//#testresult/c1f74b61b3ddb374","status":"failed","statusDetails":"AssertionError","time":{"start":1723421543257,"stop":1723421559558,"duration":16301}},{"uid":"2891a72e80ad953a","reportUrl":"https://status-im.github.io/status-cli-tests/159//#testresult/2891a72e80ad953a","status":"failed","statusDetails":"AssertionError","time":{"start":1723335215748,"stop":1723335232220,"duration":16472}},{"uid":"8da31e60fcdd0479","reportUrl":"https://status-im.github.io/status-cli-tests/158//#testresult/8da31e60fcdd0479","status":"failed","statusDetails":"AssertionError","time":{"start":1723248744837,"stop":1723248761295,"duration":16458}},{"uid":"8d866bb2f203d549","reportUrl":"https://status-im.github.io/status-cli-tests/157//#testresult/8d866bb2f203d549","status":"failed","statusDetails":"AssertionError","time":{"start":1723162382777,"stop":1723162406095,"duration":23318}},{"uid":"6108921eea17eddc","reportUrl":"https://status-im.github.io/status-cli-tests/156//#testresult/6108921eea17eddc","status":"failed","statusDetails":"AssertionError","time":{"start":1723075965101,"stop":1723075981532,"duration":16431}},{"uid":"65c544f30e73bb94","reportUrl":"https://status-im.github.io/status-cli-tests/155//#testresult/65c544f30e73bb94","status":"passed","time":{"start":1722989793667,"stop":1722989831321,"duration":37654}},{"uid":"7950b94fdc19293c","reportUrl":"https://status-im.github.io/status-cli-tests/154//#testresult/7950b94fdc19293c","status":"passed","time":{"start":1722903376749,"stop":1722903407298,"duration":30549}},{"uid":"38ec020fdb4ffe21","reportUrl":"https://status-im.github.io/status-cli-tests/153//#testresult/38ec020fdb4ffe21","status":"passed","time":{"start":1722817020354,"stop":1722817056401,"duration":36047}},{"uid":"aac32a4e39b5b473","reportUrl":"https://status-im.github.io/status-cli-tests/152//#testresult/aac32a4e39b5b473","status":"passed","time":{"start":1722730659364,"stop":1722730691265,"duration":31901}},{"uid":"e02d30ad740558d9","reportUrl":"https://status-im.github.io/status-cli-tests/151//#testresult/e02d30ad740558d9","status":"passed","time":{"start":1722644197816,"stop":1722644228670,"duration":30854}},{"uid":"91d4c8dcdc5ed1b3","reportUrl":"https://status-im.github.io/status-cli-tests/150//#testresult/91d4c8dcdc5ed1b3","status":"passed","time":{"start":1722557783211,"stop":1722557814302,"duration":31091}},{"uid":"84582dfcb7794a69","reportUrl":"https://status-im.github.io/status-cli-tests/149//#testresult/84582dfcb7794a69","status":"passed","time":{"start":1722471422347,"stop":1722471458773,"duration":36426}},{"uid":"7d5ad1deac2ad90c","reportUrl":"https://status-im.github.io/status-cli-tests/148//#testresult/7d5ad1deac2ad90c","status":"failed","statusDetails":"AssertionError","time":{"start":1722384916343,"stop":1722384936698,"duration":20355}},{"uid":"22f5ba7cb9fb8751","reportUrl":"https://status-im.github.io/status-cli-tests/147//#testresult/22f5ba7cb9fb8751","status":"passed","time":{"start":1722298585607,"stop":1722298615974,"duration":30367}},{"uid":"958f6df848c7de7d","reportUrl":"https://status-im.github.io/status-cli-tests/146//#testresult/958f6df848c7de7d","status":"passed","time":{"start":1722212200145,"stop":1722212230394,"duration":30249}},{"uid":"fdb7a11f7975b38c","reportUrl":"https://status-im.github.io/status-cli-tests/145//#testresult/fdb7a11f7975b38c","status":"passed","time":{"start":1722125868040,"stop":1722125898371,"duration":30331}},{"uid":"363af369d8b0f3da","reportUrl":"https://status-im.github.io/status-cli-tests/144//#testresult/363af369d8b0f3da","status":"passed","time":{"start":1722039377348,"stop":1722039407614,"duration":30266}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"95bf815e9de23ad4.json","parameterValues":[]}