{"uid":"72c7c04dd23734f8","name":"test_join_community_with_packet_loss","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_packet_loss","historyId":"447b5e60edf20b9d6546c17e4d82b687","time":{"start":1740875727477,"stop":1740875834697,"duration":107220},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:5208 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:1430: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5208): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5208): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:5208 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1740874564234,"stop":1740874564234,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1740875719668,"stop":1740875719668,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1740875719668,"stop":1740875719668,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1740875719668,"stop":1740875727477,"duration":7809},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:5208 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:1430: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=5208): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5208): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:5208 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"2a6d4ed4c91fb85a","name":"log","source":"2a6d4ed4c91fb85a.txt","type":"text/plain","size":138144}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1740875834869,"stop":1740875834872,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1740875834872,"stop":1740875834991,"duration":119},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1740876421826,"stop":1740876421826,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az1391-660"},{"name":"thread","value":"50795-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":24,"broken":108,"skipped":0,"passed":13,"unknown":0,"total":145},"items":[{"uid":"ad156fb9438176e8","reportUrl":"https://status-im.github.io/status-cli-tests/383//#testresult/ad156fb9438176e8","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:55418 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740789309614,"stop":1740789364062,"duration":54448}},{"uid":"5b0b0b5d9b195b4c","reportUrl":"https://status-im.github.io/status-cli-tests/382//#testresult/5b0b0b5d9b195b4c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:58906 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740702793412,"stop":1740702869894,"duration":76482}},{"uid":"b068b14ec676796f","reportUrl":"https://status-im.github.io/status-cli-tests/381//#testresult/b068b14ec676796f","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:19734 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740616422886,"stop":1740616506895,"duration":84009}},{"uid":"f41b5a43067ac82c","reportUrl":"https://status-im.github.io/status-cli-tests/380//#testresult/f41b5a43067ac82c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:59492 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740529986845,"stop":1740530067447,"duration":80602}},{"uid":"de495dcb64a87c6b","reportUrl":"https://status-im.github.io/status-cli-tests/379//#testresult/de495dcb64a87c6b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:63018 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740443506816,"stop":1740443561265,"duration":54449}},{"uid":"21da93c92e10f996","reportUrl":"https://status-im.github.io/status-cli-tests/378//#testresult/21da93c92e10f996","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:29639 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740357083238,"stop":1740357137686,"duration":54448}},{"uid":"1b1fa6872dfbcefa","reportUrl":"https://status-im.github.io/status-cli-tests/377//#testresult/1b1fa6872dfbcefa","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:8280 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740270780387,"stop":1740270834823,"duration":54436}},{"uid":"fe8e86f1384821a6","reportUrl":"https://status-im.github.io/status-cli-tests/376//#testresult/fe8e86f1384821a6","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:34198 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740184508374,"stop":1740184562828,"duration":54454}},{"uid":"8c11aeb498ecc25f","reportUrl":"https://status-im.github.io/status-cli-tests/375//#testresult/8c11aeb498ecc25f","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:11946 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1740097867638,"stop":1740097922085,"duration":54447}},{"uid":"da7844bbe6e3e25b","reportUrl":"https://status-im.github.io/status-cli-tests/374//#testresult/da7844bbe6e3e25b","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1740011456171,"stop":1740011518453,"duration":62282}},{"uid":"5a6c2be90d431e0c","reportUrl":"https://status-im.github.io/status-cli-tests/373//#testresult/5a6c2be90d431e0c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:33780 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739924874942,"stop":1739924929376,"duration":54434}},{"uid":"90b8c9435a474f40","reportUrl":"https://status-im.github.io/status-cli-tests/372//#testresult/90b8c9435a474f40","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:64588 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739838669582,"stop":1739838724018,"duration":54436}},{"uid":"b29d22d31423fe98","reportUrl":"https://status-im.github.io/status-cli-tests/371//#testresult/b29d22d31423fe98","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:20029 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739752435789,"stop":1739752490242,"duration":54453}},{"uid":"de29130cde7f94da","reportUrl":"https://status-im.github.io/status-cli-tests/370//#testresult/de29130cde7f94da","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:17155 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739666055708,"stop":1739666110154,"duration":54446}},{"uid":"f0db7ea3c0e76ed","reportUrl":"https://status-im.github.io/status-cli-tests/369//#testresult/f0db7ea3c0e76ed","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:9946 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739579504850,"stop":1739579559288,"duration":54438}},{"uid":"2b01a9f6df2d1e1c","reportUrl":"https://status-im.github.io/status-cli-tests/368//#testresult/2b01a9f6df2d1e1c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1739493141116,"stop":1739493190513,"duration":49397}},{"uid":"73ad2653aae87967","reportUrl":"https://status-im.github.io/status-cli-tests/367//#testresult/73ad2653aae87967","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:13547 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739406730340,"stop":1739406784781,"duration":54441}},{"uid":"fdc7831aea04118e","reportUrl":"https://status-im.github.io/status-cli-tests/366//#testresult/fdc7831aea04118e","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:8587 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739320384806,"stop":1739320455668,"duration":70862}},{"uid":"e6b947790494b804","reportUrl":"https://status-im.github.io/status-cli-tests/365//#testresult/e6b947790494b804","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:35759 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739233908440,"stop":1739233962888,"duration":54448}},{"uid":"320c573dd344fc77","reportUrl":"https://status-im.github.io/status-cli-tests/364//#testresult/320c573dd344fc77","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:21993 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739147481184,"stop":1739147581943,"duration":100759}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"72c7c04dd23734f8.json","parameterValues":[]}