{"uid":"478e2bf91aca3b78","name":"test_fetch_community_with_packet_loss","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_packet_loss","historyId":"0eca0edbd90df8c1e44c54fb8592b7c8","time":{"start":1724459799727,"stop":1724459854207,"duration":54480},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:39: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)","flaky":true,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1724458222760,"stop":1724458222760,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1724459791917,"stop":1724459791917,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1724459791918,"stop":1724459799727,"duration":7809},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1724459791918,"stop":1724459791918,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:39: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38314): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"599c2c75c5a3c340","name":"log","source":"599c2c75c5a3c340.txt","type":"text/plain","size":146302}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1724459854415,"stop":1724459854418,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1724459854418,"stop":1724459854592,"duration":174},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1724461517932,"stop":1724461517932,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1501-910"},{"name":"thread","value":"10176-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":4,"broken":32,"skipped":0,"passed":9,"unknown":0,"total":45},"items":[{"uid":"73c9ce9852f6a36d","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/73c9ce9852f6a36d","status":"passed","time":{"start":1724373372643,"stop":1724373412924,"duration":40281}},{"uid":"fe77a17c6134107","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/fe77a17c6134107","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x039a5d0e72a935608ee196d0ccd9d9b14cbb37b4fb2c1c3c07e6ef2c36b5efeef9, Error: 'NoneType' object is not subscriptable","time":{"start":1724286930272,"stop":1724286974596,"duration":44324}},{"uid":"131ff6513c4ff25f","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/131ff6513c4ff25f","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=53325): Read timed out. (read timeout=10)","time":{"start":1724256874615,"stop":1724256951121,"duration":76506}},{"uid":"f4884401fd59e48","reportUrl":"https://status-im.github.io/status-cli-tests/174//#testresult/f4884401fd59e48","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=37908): Read timed out. (read timeout=10)","time":{"start":1724242166442,"stop":1724242260566,"duration":94124}},{"uid":"90011b4c58282453","reportUrl":"https://status-im.github.io/status-cli-tests/173//#testresult/90011b4c58282453","status":"passed","time":{"start":1724236697219,"stop":1724236742828,"duration":45609}},{"uid":"983d4c641db290e2","reportUrl":"https://status-im.github.io/status-cli-tests/172//#testresult/983d4c641db290e2","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42839): Read timed out. (read timeout=2)","time":{"start":1724200551208,"stop":1724200596424,"duration":45216}},{"uid":"82fab715fd1e1c26","reportUrl":"https://status-im.github.io/status-cli-tests/171//#testresult/82fab715fd1e1c26","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=33694): Read timed out. (read timeout=2)","time":{"start":1724161536906,"stop":1724161588343,"duration":51437}},{"uid":"c24fb042d718f2d3","reportUrl":"https://status-im.github.io/status-cli-tests/170//#testresult/c24fb042d718f2d3","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=9177): Read timed out. (read timeout=2)","time":{"start":1724157159380,"stop":1724157205214,"duration":45834}},{"uid":"402c721e0f748643","reportUrl":"https://status-im.github.io/status-cli-tests/168//#testresult/402c721e0f748643","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=2228): Read timed out. (read timeout=2)","time":{"start":1724113875312,"stop":1724113920535,"duration":45223}},{"uid":"8326452e8eff9584","reportUrl":"https://status-im.github.io/status-cli-tests/167//#testresult/8326452e8eff9584","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=15379): Read timed out. (read timeout=2)","time":{"start":1724027472426,"stop":1724027535504,"duration":63078}},{"uid":"e2028804ac0d59a7","reportUrl":"https://status-im.github.io/status-cli-tests/166//#testresult/e2028804ac0d59a7","status":"failed","statusDetails":"AssertionError: 9 community fetches out of 10: ,Community ID: 0x03a6a7f854fcbecfbedec96f4b97de31050cddbe720bfbeb4364c55522cfc89aac, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x0341aa32012cd4a5d448c65739e7947c11c5687062717d3a881d351cbde3d6bb71, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03e505e10595c1778fb2474f515d5d1cb848ff5f320bc30815ba7b138619e2842b, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x029e331b901472432e6ac830050dc9f20f79245c4f22fb734c39608aaf68be1070, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02a102045a149f48666166ec79174846c400268065b1d0489b49c833d2270a71bc, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03dfe31201635ab2468eebbcf616cdfa0ffa777274cee57788507655c4628eb3f4, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039bcfa68f2a504579c3fe135783ac9d16796a52a0a0bb0b1f6c31c2e28944b278, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039af3d3e15ccdbdb8a2f8a53010710716c485b5224ee14e01ecaf445d6caac091, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x032c0553a8594b714366bbfb6e5715b076f00757d0a9146146292dd930969a3fab, Error: 'NoneType' object is not subscriptable","time":{"start":1723941161916,"stop":1723941212975,"duration":51059}},{"uid":"db04c6ad636d3b0c","reportUrl":"https://status-im.github.io/status-cli-tests/165//#testresult/db04c6ad636d3b0c","status":"failed","statusDetails":"AssertionError: 9 community fetches out of 10: ,Community ID: 0x03a6a7f854fcbecfbedec96f4b97de31050cddbe720bfbeb4364c55522cfc89aac, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x0341aa32012cd4a5d448c65739e7947c11c5687062717d3a881d351cbde3d6bb71, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03e505e10595c1778fb2474f515d5d1cb848ff5f320bc30815ba7b138619e2842b, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x029e331b901472432e6ac830050dc9f20f79245c4f22fb734c39608aaf68be1070, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02a102045a149f48666166ec79174846c400268065b1d0489b49c833d2270a71bc, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03dfe31201635ab2468eebbcf616cdfa0ffa777274cee57788507655c4628eb3f4, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039bcfa68f2a504579c3fe135783ac9d16796a52a0a0bb0b1f6c31c2e28944b278, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039af3d3e15ccdbdb8a2f8a53010710716c485b5224ee14e01ecaf445d6caac091, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x032c0553a8594b714366bbfb6e5715b076f00757d0a9146146292dd930969a3fab, Error: 'NoneType' object is not subscriptable","time":{"start":1723854687140,"stop":1723854726651,"duration":39511}},{"uid":"42c08e34cd03e61c","reportUrl":"https://status-im.github.io/status-cli-tests/164//#testresult/42c08e34cd03e61c","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=62806): Read timed out. (read timeout=2)","time":{"start":1723768326749,"stop":1723768371980,"duration":45231}},{"uid":"49f4a9c9864640bc","reportUrl":"https://status-im.github.io/status-cli-tests/163//#testresult/49f4a9c9864640bc","status":"failed","statusDetails":"AssertionError: 8 community fetches out of 10: ,Community ID: 0x03a6a7f854fcbecfbedec96f4b97de31050cddbe720bfbeb4364c55522cfc89aac, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x0341aa32012cd4a5d448c65739e7947c11c5687062717d3a881d351cbde3d6bb71, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03e505e10595c1778fb2474f515d5d1cb848ff5f320bc30815ba7b138619e2842b, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x02a102045a149f48666166ec79174846c400268065b1d0489b49c833d2270a71bc, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x03dfe31201635ab2468eebbcf616cdfa0ffa777274cee57788507655c4628eb3f4, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039bcfa68f2a504579c3fe135783ac9d16796a52a0a0bb0b1f6c31c2e28944b278, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x039af3d3e15ccdbdb8a2f8a53010710716c485b5224ee14e01ecaf445d6caac091, Error: 'NoneType' object is not subscriptable\n,Community ID: 0x032c0553a8594b714366bbfb6e5715b076f00757d0a9146146292dd930969a3fab, Error: 'NoneType' object is not subscriptable","time":{"start":1723681886021,"stop":1723681926569,"duration":40548}},{"uid":"97e50e9ded8c56f0","reportUrl":"https://status-im.github.io/status-cli-tests/162//#testresult/97e50e9ded8c56f0","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=18258): Read timed out. (read timeout=2)","time":{"start":1723595459105,"stop":1723595504318,"duration":45213}},{"uid":"98cbb41dcbe1ad18","reportUrl":"https://status-im.github.io/status-cli-tests/161//#testresult/98cbb41dcbe1ad18","status":"passed","time":{"start":1723509085693,"stop":1723509141076,"duration":55383}},{"uid":"922ee9e318363572","reportUrl":"https://status-im.github.io/status-cli-tests/160//#testresult/922ee9e318363572","status":"passed","time":{"start":1723422642719,"stop":1723422685010,"duration":42291}},{"uid":"f4ff2f7806194363","reportUrl":"https://status-im.github.io/status-cli-tests/159//#testresult/f4ff2f7806194363","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=43439): Read timed out. (read timeout=2)","time":{"start":1723336387744,"stop":1723336432970,"duration":45226}},{"uid":"de4ef6e660a99f4b","reportUrl":"https://status-im.github.io/status-cli-tests/158//#testresult/de4ef6e660a99f4b","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=51081): Read timed out. (read timeout=2)","time":{"start":1723249891361,"stop":1723249936580,"duration":45219}},{"uid":"b0df0625728cc315","reportUrl":"https://status-im.github.io/status-cli-tests/157//#testresult/b0df0625728cc315","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=5277): Read timed out. (read timeout=2)","time":{"start":1723163580598,"stop":1723163626086,"duration":45488}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"478e2bf91aca3b78.json","parameterValues":[]}