{"uid":"2f8e3f1d1a8092d4","name":"test_fetch_community_with_packet_loss","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_packet_loss","historyId":"0eca0edbd90df8c1e44c54fb8592b7c8","time":{"start":1738715243727,"stop":1738715320545,"duration":76818},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:54525 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=54525): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=54525): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:54525 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1738714587661,"stop":1738714587661,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1738715235914,"stop":1738715235914,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1738715235914,"stop":1738715235914,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1738715235915,"stop":1738715243726,"duration":7811},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:54525 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=54525): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=54525): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:54525 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"80803ca94e7ddf70","name":"log","source":"80803ca94e7ddf70.txt","type":"text/plain","size":105270}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1738715320720,"stop":1738715320722,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1738715320722,"stop":1738715320846,"duration":124},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1738716118401,"stop":1738716118402,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1696-133"},{"name":"thread","value":"60488-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":3,"broken":88,"skipped":0,"passed":29,"unknown":0,"total":120},"items":[{"uid":"ffe75ab65e50d941","reportUrl":"https://status-im.github.io/status-cli-tests/358//#testresult/ffe75ab65e50d941","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:29787 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738628950722,"stop":1738629007129,"duration":56407}},{"uid":"ac35038765fbc4d4","reportUrl":"https://status-im.github.io/status-cli-tests/357//#testresult/ac35038765fbc4d4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:60060 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738542481190,"stop":1738542562033,"duration":80843}},{"uid":"7952967a43f11e19","reportUrl":"https://status-im.github.io/status-cli-tests/356//#testresult/7952967a43f11e19","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:2226 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738456085750,"stop":1738456146820,"duration":61070}},{"uid":"1f7934515811ff61","reportUrl":"https://status-im.github.io/status-cli-tests/355//#testresult/1f7934515811ff61","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:44477 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738369715960,"stop":1738369789014,"duration":73054}},{"uid":"ecb609816790c2c5","reportUrl":"https://status-im.github.io/status-cli-tests/354//#testresult/ecb609816790c2c5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:50700 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738283211385,"stop":1738283302480,"duration":91095}},{"uid":"39186ed334f202b7","reportUrl":"https://status-im.github.io/status-cli-tests/353//#testresult/39186ed334f202b7","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2, Error: 'NoneType' object is not subscriptable","time":{"start":1738196889364,"stop":1738196953375,"duration":64011}},{"uid":"60e5c4f8a4312323","reportUrl":"https://status-im.github.io/status-cli-tests/352//#testresult/60e5c4f8a4312323","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:61028 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738110456461,"stop":1738110519597,"duration":63136}},{"uid":"81d5d9c0e492268b","reportUrl":"https://status-im.github.io/status-cli-tests/351//#testresult/81d5d9c0e492268b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:65359 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738024074650,"stop":1738024155749,"duration":81099}},{"uid":"811557eb76b2ff0a","reportUrl":"https://status-im.github.io/status-cli-tests/350//#testresult/811557eb76b2ff0a","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62168 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737937654268,"stop":1737937728903,"duration":74635}},{"uid":"e6e28e39f8dfdc57","reportUrl":"https://status-im.github.io/status-cli-tests/349//#testresult/e6e28e39f8dfdc57","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:18891 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737851323254,"stop":1737851445875,"duration":122621}},{"uid":"abfb1f9e57163e8a","reportUrl":"https://status-im.github.io/status-cli-tests/348//#testresult/abfb1f9e57163e8a","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:39508 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737764801127,"stop":1737764859512,"duration":58385}},{"uid":"51d5b9d892261f07","reportUrl":"https://status-im.github.io/status-cli-tests/347//#testresult/51d5b9d892261f07","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2, Error: 'NoneType' object is not subscriptable","time":{"start":1737678451681,"stop":1737678518677,"duration":66996}},{"uid":"e2c32cbccf45cfaf","reportUrl":"https://status-im.github.io/status-cli-tests/346//#testresult/e2c32cbccf45cfaf","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:37934 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737592028356,"stop":1737592082787,"duration":54431}},{"uid":"ec327d1265f49feb","reportUrl":"https://status-im.github.io/status-cli-tests/345//#testresult/ec327d1265f49feb","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:41848 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737505607415,"stop":1737505661859,"duration":54444}},{"uid":"8bfa9ba92b70f357","reportUrl":"https://status-im.github.io/status-cli-tests/344//#testresult/8bfa9ba92b70f357","status":"passed","time":{"start":1737419130805,"stop":1737419223593,"duration":92788}},{"uid":"e891f26d1dbeda61","reportUrl":"https://status-im.github.io/status-cli-tests/343//#testresult/e891f26d1dbeda61","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:16512 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737332740499,"stop":1737332792926,"duration":52427}},{"uid":"954521184817af55","reportUrl":"https://status-im.github.io/status-cli-tests/342//#testresult/954521184817af55","status":"passed","time":{"start":1737246366684,"stop":1737246418784,"duration":52100}},{"uid":"58aa4586cc4e232","reportUrl":"https://status-im.github.io/status-cli-tests/341//#testresult/58aa4586cc4e232","status":"passed","time":{"start":1737159918455,"stop":1737159953611,"duration":35156}},{"uid":"a4253164ccf32621","reportUrl":"https://status-im.github.io/status-cli-tests/340//#testresult/a4253164ccf32621","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:28687 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737073575246,"stop":1737073657313,"duration":82067}},{"uid":"f3b8fcbd0d5a0559","reportUrl":"https://status-im.github.io/status-cli-tests/339//#testresult/f3b8fcbd0d5a0559","status":"passed","time":{"start":1736987155127,"stop":1736987210305,"duration":55178}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"2f8e3f1d1a8092d4.json","parameterValues":[]}