{"uid":"c0ed439685b468d0","name":"test_join_community_with_packet_loss","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_packet_loss","historyId":"447b5e60edf20b9d6546c17e4d82b687","time":{"start":1738715592400,"stop":1738715646850,"duration":54450},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:38196 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=38196): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38196): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:38196 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1738714587661,"stop":1738714587661,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1738715584587,"stop":1738715584588,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1738715584588,"stop":1738715592400,"duration":7812},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1738715584588,"stop":1738715584588,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:38196 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=38196): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=38196): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:60: in test_join_community_with_packet_loss\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:38196 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"40960f5cef20756e","name":"log","source":"40960f5cef20756e.txt","type":"text/plain","size":107695}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1738715647036,"stop":1738715647039,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1738715647039,"stop":1738715647157,"duration":118},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1738716118401,"stop":1738716118402,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az1696-133"},{"name":"thread","value":"60488-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":22,"broken":85,"skipped":0,"passed":13,"unknown":0,"total":120},"items":[{"uid":"6f134e13ba6275a6","reportUrl":"https://status-im.github.io/status-cli-tests/358//#testresult/6f134e13ba6275a6","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:36359 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738629305749,"stop":1738629383286,"duration":77537}},{"uid":"5ad761184af8e428","reportUrl":"https://status-im.github.io/status-cli-tests/357//#testresult/5ad761184af8e428","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:56763 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738542864055,"stop":1738542948590,"duration":84535}},{"uid":"2cc52e204401f88","reportUrl":"https://status-im.github.io/status-cli-tests/356//#testresult/2cc52e204401f88","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1738456437357,"stop":1738456521889,"duration":84532}},{"uid":"72699d52ad8db19c","reportUrl":"https://status-im.github.io/status-cli-tests/355//#testresult/72699d52ad8db19c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:48195 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738369979649,"stop":1738370038421,"duration":58772}},{"uid":"b49ce2b48f905e6c","reportUrl":"https://status-im.github.io/status-cli-tests/354//#testresult/b49ce2b48f905e6c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:56050 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738283483315,"stop":1738283567194,"duration":83879}},{"uid":"fe83398cf77c8596","reportUrl":"https://status-im.github.io/status-cli-tests/353//#testresult/fe83398cf77c8596","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:47303 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738197238013,"stop":1738197295114,"duration":57101}},{"uid":"af855d78081012a1","reportUrl":"https://status-im.github.io/status-cli-tests/352//#testresult/af855d78081012a1","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:47296 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738110834286,"stop":1738110888730,"duration":54444}},{"uid":"a5194560463addc8","reportUrl":"https://status-im.github.io/status-cli-tests/351//#testresult/a5194560463addc8","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:25279 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738024441370,"stop":1738024561737,"duration":120367}},{"uid":"7f893700672bf49b","reportUrl":"https://status-im.github.io/status-cli-tests/350//#testresult/7f893700672bf49b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:6381 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737938005223,"stop":1737938101129,"duration":95906}},{"uid":"40c55d1392d0fccd","reportUrl":"https://status-im.github.io/status-cli-tests/349//#testresult/40c55d1392d0fccd","status":"passed","time":{"start":1737851737978,"stop":1737851852520,"duration":114542}},{"uid":"df1b83a8ddfdf767","reportUrl":"https://status-im.github.io/status-cli-tests/348//#testresult/df1b83a8ddfdf767","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:19571 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737765147381,"stop":1737765206421,"duration":59040}},{"uid":"d20f0239d265b54","reportUrl":"https://status-im.github.io/status-cli-tests/347//#testresult/d20f0239d265b54","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:13105 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737678821500,"stop":1737678889264,"duration":67764}},{"uid":"8f6410193cc2d2a7","reportUrl":"https://status-im.github.io/status-cli-tests/346//#testresult/8f6410193cc2d2a7","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:4659 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737592340031,"stop":1737592394473,"duration":54442}},{"uid":"696e54462ecd55c6","reportUrl":"https://status-im.github.io/status-cli-tests/345//#testresult/696e54462ecd55c6","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:37190 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737505913776,"stop":1737505968228,"duration":54452}},{"uid":"eebb02ac366adc25","reportUrl":"https://status-im.github.io/status-cli-tests/344//#testresult/eebb02ac366adc25","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:63000 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737419379792,"stop":1737419436233,"duration":56441}},{"uid":"3e92c469c91dd24c","reportUrl":"https://status-im.github.io/status-cli-tests/343//#testresult/3e92c469c91dd24c","status":"passed","time":{"start":1737332946818,"stop":1737333015989,"duration":69171}},{"uid":"ffa64ee49066741","reportUrl":"https://status-im.github.io/status-cli-tests/342//#testresult/ffa64ee49066741","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:5552 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737246569447,"stop":1737246665878,"duration":96431}},{"uid":"bf9e72bcb30480","reportUrl":"https://status-im.github.io/status-cli-tests/341//#testresult/bf9e72bcb30480","status":"passed","time":{"start":1737160114848,"stop":1737160198883,"duration":84035}},{"uid":"637e19a8c802cda5","reportUrl":"https://status-im.github.io/status-cli-tests/340//#testresult/637e19a8c802cda5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:50698 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737073820295,"stop":1737073875202,"duration":54907}},{"uid":"38ebd6feb599ad0a","reportUrl":"https://status-im.github.io/status-cli-tests/339//#testresult/38ebd6feb599ad0a","status":"passed","time":{"start":1736987367671,"stop":1736987413017,"duration":45346}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"c0ed439685b468d0.json","parameterValues":[]}