{"uid":"460671bc98bd4d54","name":"test_fetch_community_baseline","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_baseline","historyId":"9064524ab27e4d2f05b36e3169041aa0","time":{"start":1725755653399,"stop":1725755708983,"duration":55584},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1725754298879,"stop":1725754298879,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1725755645588,"stop":1725755645588,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1725755645588,"stop":1725755645588,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1725755645588,"stop":1725755653398,"duration":7810},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:19: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=48302): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"c8c64b66eb592611","name":"log","source":"c8c64b66eb592611.txt","type":"text/plain","size":135978}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1725755709224,"stop":1725755709226,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1725755709226,"stop":1725755709380,"duration":154},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1725757253577,"stop":1725757253577,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az568-675"},{"name":"thread","value":"10195-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":8,"broken":12,"skipped":0,"passed":40,"unknown":0,"total":60},"items":[{"uid":"66088962aed64c98","reportUrl":"https://status-im.github.io/status-cli-tests/192//#testresult/66088962aed64c98","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11260): Read timed out. (read timeout=10)","time":{"start":1725669164201,"stop":1725669218692,"duration":54491}},{"uid":"64c0f3bc9ec81af0","reportUrl":"https://status-im.github.io/status-cli-tests/191//#testresult/64c0f3bc9ec81af0","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=35308): Read timed out. (read timeout=10)","time":{"start":1725582769241,"stop":1725582825078,"duration":55837}},{"uid":"78368d6ca093860e","reportUrl":"https://status-im.github.io/status-cli-tests/190//#testresult/78368d6ca093860e","status":"passed","time":{"start":1725496451022,"stop":1725496510314,"duration":59292}},{"uid":"5de1fe513cfa44d6","reportUrl":"https://status-im.github.io/status-cli-tests/189//#testresult/5de1fe513cfa44d6","status":"passed","time":{"start":1725409917507,"stop":1725409946295,"duration":28788}},{"uid":"49e9bce0343c6ea1","reportUrl":"https://status-im.github.io/status-cli-tests/188//#testresult/49e9bce0343c6ea1","status":"passed","time":{"start":1725323512057,"stop":1725323539878,"duration":27821}},{"uid":"e9cdee79e5b70e67","reportUrl":"https://status-im.github.io/status-cli-tests/187//#testresult/e9cdee79e5b70e67","status":"passed","time":{"start":1725237067491,"stop":1725237097282,"duration":29791}},{"uid":"d3ec625a551df654","reportUrl":"https://status-im.github.io/status-cli-tests/186//#testresult/d3ec625a551df654","status":"passed","time":{"start":1725150933548,"stop":1725150962338,"duration":28790}},{"uid":"4ba3b910c88f85d1","reportUrl":"https://status-im.github.io/status-cli-tests/185//#testresult/4ba3b910c88f85d1","status":"passed","time":{"start":1725064504926,"stop":1725064532551,"duration":27625}},{"uid":"c8756e369e6945eb","reportUrl":"https://status-im.github.io/status-cli-tests/184//#testresult/c8756e369e6945eb","status":"passed","time":{"start":1724978069748,"stop":1724978096409,"duration":26661}},{"uid":"903cdfe812153289","reportUrl":"https://status-im.github.io/status-cli-tests/183//#testresult/903cdfe812153289","status":"passed","time":{"start":1724891754762,"stop":1724891785123,"duration":30361}},{"uid":"3578a9a0688edfb6","reportUrl":"https://status-im.github.io/status-cli-tests/182//#testresult/3578a9a0688edfb6","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=26219): Read timed out. (read timeout=10)","time":{"start":1724805318467,"stop":1724805454564,"duration":136097}},{"uid":"55d1250f4ca4d9dc","reportUrl":"https://status-im.github.io/status-cli-tests/181//#testresult/55d1250f4ca4d9dc","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=56589): Read timed out. (read timeout=10)","time":{"start":1724718955583,"stop":1724719044317,"duration":88734}},{"uid":"3eaf25bd39c8911","reportUrl":"https://status-im.github.io/status-cli-tests/180//#testresult/3eaf25bd39c8911","status":"passed","time":{"start":1724632718013,"stop":1724632777954,"duration":59941}},{"uid":"4bd0645706ece069","reportUrl":"https://status-im.github.io/status-cli-tests/179//#testresult/4bd0645706ece069","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=13753): Read timed out. (read timeout=10)","time":{"start":1724546269075,"stop":1724546323566,"duration":54491}},{"uid":"8806530faa90de75","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/8806530faa90de75","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61871): Read timed out. (read timeout=10)","time":{"start":1724459666751,"stop":1724459728855,"duration":62104}},{"uid":"7cbad93236ad7511","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/7cbad93236ad7511","status":"passed","time":{"start":1724373271158,"stop":1724373300781,"duration":29623}},{"uid":"4df5b4bc8fc3583d","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/4df5b4bc8fc3583d","status":"passed","time":{"start":1724286805246,"stop":1724286835357,"duration":30111}},{"uid":"db0f8fdcc0f97694","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/db0f8fdcc0f97694","status":"passed","time":{"start":1724256773862,"stop":1724256803798,"duration":29936}},{"uid":"41d9a65f2fa61259","reportUrl":"https://status-im.github.io/status-cli-tests/174//#testresult/41d9a65f2fa61259","status":"passed","time":{"start":1724242050934,"stop":1724242080618,"duration":29684}},{"uid":"d741906d81568413","reportUrl":"https://status-im.github.io/status-cli-tests/173//#testresult/d741906d81568413","status":"passed","time":{"start":1724236594842,"stop":1724236623023,"duration":28181}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"460671bc98bd4d54.json","parameterValues":[]}