{"uid":"4f49424621db8ea3","name":"test_join_community_with_low_bandwith","fullName":"tests.test_join_community.TestJoinCommunity#test_join_community_with_low_bandwith","historyId":"acec66a9fe6a2fbcbf702c9ea545d881","time":{"start":1730508277378,"stop":1730508331887,"duration":54509},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:59980 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=59980): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=59980): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:65: in test_join_community_with_low_bandwith\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:59980 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1730506565728,"stop":1730506565728,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1730508269567,"stop":1730508269568,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1730508269568,"stop":1730508269568,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1730508269568,"stop":1730508277378,"duration":7810},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:59980 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=59980): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=59980): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_join_community.py:65: in test_join_community_with_low_bandwith\n    self.test_join_community_baseline()\ntests/test_join_community.py:19: in test_join_community_baseline\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:59980 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"ae01a308d28135d3","name":"log","source":"ae01a308d28135d3.txt","type":"text/plain","size":39537}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1730508332128,"stop":1730508332130,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1730508332131,"stop":1730508332385,"duration":254},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1730509041639,"stop":1730509041639,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_join_community"},{"name":"subSuite","value":"TestJoinCommunity"},{"name":"host","value":"fv-az885-39"},{"name":"thread","value":"76790-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_join_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":13,"broken":1,"skipped":0,"passed":10,"unknown":0,"total":24},"items":[{"uid":"219b185c392ccc68","reportUrl":"https://status-im.github.io/status-cli-tests/261//#testresult/219b185c392ccc68","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730421830766,"stop":1730421886300,"duration":55534}},{"uid":"2560b23fb638b264","reportUrl":"https://status-im.github.io/status-cli-tests/260//#testresult/2560b23fb638b264","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730335249028,"stop":1730335304783,"duration":55755}},{"uid":"98591b22efccc3ab","reportUrl":"https://status-im.github.io/status-cli-tests/259//#testresult/98591b22efccc3ab","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730248865118,"stop":1730248925381,"duration":60263}},{"uid":"5bbdff6a663ec880","reportUrl":"https://status-im.github.io/status-cli-tests/258//#testresult/5bbdff6a663ec880","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730162342584,"stop":1730162398168,"duration":55584}},{"uid":"f7ae015e257c9fe3","reportUrl":"https://status-im.github.io/status-cli-tests/257//#testresult/f7ae015e257c9fe3","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1730075847677,"stop":1730075901994,"duration":54317}},{"uid":"69996d8cf48f4844","reportUrl":"https://status-im.github.io/status-cli-tests/256//#testresult/69996d8cf48f4844","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729989476165,"stop":1729989530637,"duration":54472}},{"uid":"9776a4c832ad95d3","reportUrl":"https://status-im.github.io/status-cli-tests/255//#testresult/9776a4c832ad95d3","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729903049709,"stop":1729903107728,"duration":58019}},{"uid":"db7b108766b2484a","reportUrl":"https://status-im.github.io/status-cli-tests/254//#testresult/db7b108766b2484a","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729816708546,"stop":1729816761705,"duration":53159}},{"uid":"9a1d96d3bc5b0f28","reportUrl":"https://status-im.github.io/status-cli-tests/253//#testresult/9a1d96d3bc5b0f28","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729730283272,"stop":1729730335293,"duration":52021}},{"uid":"460170b64656236c","reportUrl":"https://status-im.github.io/status-cli-tests/252//#testresult/460170b64656236c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729643773235,"stop":1729643824610,"duration":51375}},{"uid":"83cb66546a1c2270","reportUrl":"https://status-im.github.io/status-cli-tests/251//#testresult/83cb66546a1c2270","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729557447688,"stop":1729557498340,"duration":50652}},{"uid":"c7982244ab6041c","reportUrl":"https://status-im.github.io/status-cli-tests/250//#testresult/c7982244ab6041c","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729471015862,"stop":1729471066464,"duration":50602}},{"uid":"213d3cb5bf58e329","reportUrl":"https://status-im.github.io/status-cli-tests/249//#testresult/213d3cb5bf58e329","status":"failed","statusDetails":"AssertionError: Response does not contain 'result' key.","time":{"start":1729384686614,"stop":1729384737302,"duration":50688}},{"uid":"e7f45e148fb444ee","reportUrl":"https://status-im.github.io/status-cli-tests/248//#testresult/e7f45e148fb444ee","status":"passed","time":{"start":1729298064595,"stop":1729298104384,"duration":39789}},{"uid":"c2738ed35f1e42d8","reportUrl":"https://status-im.github.io/status-cli-tests/247//#testresult/c2738ed35f1e42d8","status":"passed","time":{"start":1729211841237,"stop":1729211884951,"duration":43714}},{"uid":"de728dab400ef857","reportUrl":"https://status-im.github.io/status-cli-tests/246//#testresult/de728dab400ef857","status":"passed","time":{"start":1729125321389,"stop":1729125361886,"duration":40497}},{"uid":"775ec3384d458948","reportUrl":"https://status-im.github.io/status-cli-tests/245//#testresult/775ec3384d458948","status":"passed","time":{"start":1729068289869,"stop":1729068329646,"duration":39777}},{"uid":"a93d848c5a3913b9","reportUrl":"https://status-im.github.io/status-cli-tests/244//#testresult/a93d848c5a3913b9","status":"passed","time":{"start":1729039339008,"stop":1729039380495,"duration":41487}},{"uid":"e13d48242c00a461","reportUrl":"https://status-im.github.io/status-cli-tests/243//#testresult/e13d48242c00a461","status":"passed","time":{"start":1729006587779,"stop":1729006629746,"duration":41967}},{"uid":"1ebce32453b83c33","reportUrl":"https://status-im.github.io/status-cli-tests/242//#testresult/1ebce32453b83c33","status":"passed","time":{"start":1729003945798,"stop":1729003985541,"duration":39743}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"4f49424621db8ea3.json","parameterValues":[]}