{"uid":"7e9d2171c9ce5a29","name":"test_fetch_community_with_packet_loss","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_packet_loss","historyId":"0eca0edbd90df8c1e44c54fb8592b7c8","time":{"start":1739579195716,"stop":1739579250148,"duration":54432},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:51579 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:1430: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=51579): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=51579): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:51579 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1739578573413,"stop":1739578573413,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1739579187906,"stop":1739579187906,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1739579187906,"stop":1739579187906,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1739579187906,"stop":1739579195716,"duration":7810},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:51579 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:1430: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=51579): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=51579): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:51579 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"4d73ed1ffae11f9e","name":"log","source":"4d73ed1ffae11f9e.txt","type":"text/plain","size":85324}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1739579250322,"stop":1739579250324,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1739579250325,"stop":1739579250455,"duration":130},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1739580014553,"stop":1739580014553,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1779-524"},{"name":"thread","value":"60565-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":4,"broken":97,"skipped":0,"passed":29,"unknown":0,"total":130},"items":[{"uid":"15efeaf50098124b","reportUrl":"https://status-im.github.io/status-cli-tests/368//#testresult/15efeaf50098124b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:57407 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739492834537,"stop":1739492888978,"duration":54441}},{"uid":"402e8d5e15fd09d8","reportUrl":"https://status-im.github.io/status-cli-tests/367//#testresult/402e8d5e15fd09d8","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2, Error: 'NoneType' object is not subscriptable","time":{"start":1739406419182,"stop":1739406476307,"duration":57125}},{"uid":"6076c378b9d988a2","reportUrl":"https://status-im.github.io/status-cli-tests/366//#testresult/6076c378b9d988a2","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:53269 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739320098569,"stop":1739320187247,"duration":88678}},{"uid":"b94d333fcb04188c","reportUrl":"https://status-im.github.io/status-cli-tests/365//#testresult/b94d333fcb04188c","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:26041 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739233643157,"stop":1739233697609,"duration":54452}},{"uid":"cf1278c9d56ec5f7","reportUrl":"https://status-im.github.io/status-cli-tests/364//#testresult/cf1278c9d56ec5f7","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:4325 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739147199224,"stop":1739147292640,"duration":93416}},{"uid":"58ba1005c7f1e8f7","reportUrl":"https://status-im.github.io/status-cli-tests/363//#testresult/58ba1005c7f1e8f7","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:7133 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1739060867052,"stop":1739060922111,"duration":55059}},{"uid":"5c44fb36546aa31b","reportUrl":"https://status-im.github.io/status-cli-tests/362//#testresult/5c44fb36546aa31b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:44199 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738974490713,"stop":1738974570361,"duration":79648}},{"uid":"215271188adf4bb4","reportUrl":"https://status-im.github.io/status-cli-tests/361//#testresult/215271188adf4bb4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:43229 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738888135520,"stop":1738888192063,"duration":56543}},{"uid":"fb64751d30e7240","reportUrl":"https://status-im.github.io/status-cli-tests/360//#testresult/fb64751d30e7240","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:34566 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738801648103,"stop":1738801751907,"duration":103804}},{"uid":"2f8e3f1d1a8092d4","reportUrl":"https://status-im.github.io/status-cli-tests/359//#testresult/2f8e3f1d1a8092d4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:54525 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738715243727,"stop":1738715320545,"duration":76818}},{"uid":"ffe75ab65e50d941","reportUrl":"https://status-im.github.io/status-cli-tests/358//#testresult/ffe75ab65e50d941","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:29787 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738628950722,"stop":1738629007129,"duration":56407}},{"uid":"ac35038765fbc4d4","reportUrl":"https://status-im.github.io/status-cli-tests/357//#testresult/ac35038765fbc4d4","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:60060 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738542481190,"stop":1738542562033,"duration":80843}},{"uid":"7952967a43f11e19","reportUrl":"https://status-im.github.io/status-cli-tests/356//#testresult/7952967a43f11e19","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:2226 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738456085750,"stop":1738456146820,"duration":61070}},{"uid":"1f7934515811ff61","reportUrl":"https://status-im.github.io/status-cli-tests/355//#testresult/1f7934515811ff61","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:44477 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738369715960,"stop":1738369789014,"duration":73054}},{"uid":"ecb609816790c2c5","reportUrl":"https://status-im.github.io/status-cli-tests/354//#testresult/ecb609816790c2c5","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:50700 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738283211385,"stop":1738283302480,"duration":91095}},{"uid":"39186ed334f202b7","reportUrl":"https://status-im.github.io/status-cli-tests/353//#testresult/39186ed334f202b7","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2, Error: 'NoneType' object is not subscriptable","time":{"start":1738196889364,"stop":1738196953375,"duration":64011}},{"uid":"60e5c4f8a4312323","reportUrl":"https://status-im.github.io/status-cli-tests/352//#testresult/60e5c4f8a4312323","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:61028 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738110456461,"stop":1738110519597,"duration":63136}},{"uid":"81d5d9c0e492268b","reportUrl":"https://status-im.github.io/status-cli-tests/351//#testresult/81d5d9c0e492268b","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:65359 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1738024074650,"stop":1738024155749,"duration":81099}},{"uid":"811557eb76b2ff0a","reportUrl":"https://status-im.github.io/status-cli-tests/350//#testresult/811557eb76b2ff0a","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:62168 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737937654268,"stop":1737937728903,"duration":74635}},{"uid":"e6e28e39f8dfdc57","reportUrl":"https://status-im.github.io/status-cli-tests/349//#testresult/e6e28e39f8dfdc57","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:18891 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1737851323254,"stop":1737851445875,"duration":122621}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"7e9d2171c9ce5a29.json","parameterValues":[]}