{"uid":"8aef3e67dba4be6c","name":"test_leave_community_with_latency","fullName":"tests.test_leave_community.TestLeaveCommunity#test_leave_community_with_latency","historyId":"79f7e4ee5aacb6424b78fe6ee6a94dab","time":{"start":1725929084007,"stop":1725929138487,"duration":54480},"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:40: in test_leave_community_with_latency\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)","flaky":true,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1725927063295,"stop":1725927063295,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1725929076297,"stop":1725929076297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1725929076297,"stop":1725929084007,"duration":7710},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1725929076297,"stop":1725929076297,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)","statusTrace":"/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_leave_community.py:40: in test_leave_community_with_latency\n    self.join_created_communities()\nsrc/steps/common.py:174: in join_created_communities\n    self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:170: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:22: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7176): Read timed out. (read timeout=10)","steps":[],"attachments":[{"uid":"f8a6121a9ff61108","name":"log","source":"f8a6121a9ff61108.txt","type":"text/plain","size":82915}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1725929138714,"stop":1725929138716,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1725929138717,"stop":1725929138890,"duration":173},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1725929990881,"stop":1725929990882,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_leave_community"},{"name":"subSuite","value":"TestLeaveCommunity"},{"name":"host","value":"fv-az1776-218"},{"name":"thread","value":"10204-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_leave_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":32,"broken":13,"skipped":0,"passed":17,"unknown":0,"total":62},"items":[{"uid":"1a67f9e15d217b89","reportUrl":"https://status-im.github.io/status-cli-tests/194//#testresult/1a67f9e15d217b89","status":"passed","time":{"start":1725842460276,"stop":1725842524377,"duration":64101}},{"uid":"a79aad1380540019","reportUrl":"https://status-im.github.io/status-cli-tests/193//#testresult/a79aad1380540019","status":"passed","time":{"start":1725756323035,"stop":1725756393842,"duration":70807}},{"uid":"378ebee9912fe96b","reportUrl":"https://status-im.github.io/status-cli-tests/192//#testresult/378ebee9912fe96b","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=28114): Read timed out. (read timeout=10)","time":{"start":1725669810063,"stop":1725669868259,"duration":58196}},{"uid":"b8d51e94250cf030","reportUrl":"https://status-im.github.io/status-cli-tests/191//#testresult/b8d51e94250cf030","status":"failed","statusDetails":"AssertionError","time":{"start":1725583415761,"stop":1725583479434,"duration":63673}},{"uid":"e9b5895ae22476fb","reportUrl":"https://status-im.github.io/status-cli-tests/190//#testresult/e9b5895ae22476fb","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=17813): Read timed out. (read timeout=10)","time":{"start":1725497093472,"stop":1725497147966,"duration":54494}},{"uid":"67148784caef124","reportUrl":"https://status-im.github.io/status-cli-tests/189//#testresult/67148784caef124","status":"failed","statusDetails":"AssertionError","time":{"start":1725410450584,"stop":1725410507547,"duration":56963}},{"uid":"8d2663ead38f8781","reportUrl":"https://status-im.github.io/status-cli-tests/188//#testresult/8d2663ead38f8781","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=42013): Read timed out. (read timeout=10)","time":{"start":1725324167099,"stop":1725324221597,"duration":54498}},{"uid":"c195ec8929714a4f","reportUrl":"https://status-im.github.io/status-cli-tests/187//#testresult/c195ec8929714a4f","status":"failed","statusDetails":"AssertionError","time":{"start":1725237623148,"stop":1725237680804,"duration":57656}},{"uid":"e83b5697e21b0dfe","reportUrl":"https://status-im.github.io/status-cli-tests/186//#testresult/e83b5697e21b0dfe","status":"passed","time":{"start":1725151435195,"stop":1725151481926,"duration":46731}},{"uid":"a00f9883c294293b","reportUrl":"https://status-im.github.io/status-cli-tests/185//#testresult/a00f9883c294293b","status":"passed","time":{"start":1725065009122,"stop":1725065056835,"duration":47713}},{"uid":"e7704a60361b4662","reportUrl":"https://status-im.github.io/status-cli-tests/184//#testresult/e7704a60361b4662","status":"passed","time":{"start":1724978599196,"stop":1724978647919,"duration":48723}},{"uid":"b59f61df02b88ac7","reportUrl":"https://status-im.github.io/status-cli-tests/183//#testresult/b59f61df02b88ac7","status":"failed","statusDetails":"AssertionError","time":{"start":1724892229194,"stop":1724892287959,"duration":58765}},{"uid":"68374e0f5bfd6870","reportUrl":"https://status-im.github.io/status-cli-tests/182//#testresult/68374e0f5bfd6870","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=10924): Read timed out. (read timeout=10)","time":{"start":1724805988817,"stop":1724806059522,"duration":70705}},{"uid":"ebc9c11a98f5c501","reportUrl":"https://status-im.github.io/status-cli-tests/181//#testresult/ebc9c11a98f5c501","status":"passed","time":{"start":1724719801046,"stop":1724719848734,"duration":47688}},{"uid":"90d4ebfb1a4484d3","reportUrl":"https://status-im.github.io/status-cli-tests/180//#testresult/90d4ebfb1a4484d3","status":"failed","statusDetails":"AssertionError","time":{"start":1724633538478,"stop":1724633615067,"duration":76589}},{"uid":"d84e6093ba59a8d0","reportUrl":"https://status-im.github.io/status-cli-tests/179//#testresult/d84e6093ba59a8d0","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=61533): Read timed out. (read timeout=10)","time":{"start":1724546934234,"stop":1724546988725,"duration":54491}},{"uid":"9668c0c21489c3b8","reportUrl":"https://status-im.github.io/status-cli-tests/178//#testresult/9668c0c21489c3b8","status":"broken","statusDetails":"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8730): Read timed out. (read timeout=10)","time":{"start":1724460592980,"stop":1724460647476,"duration":54496}},{"uid":"767679ff854770c6","reportUrl":"https://status-im.github.io/status-cli-tests/177//#testresult/767679ff854770c6","status":"passed","time":{"start":1724373821655,"stop":1724373869289,"duration":47634}},{"uid":"1e4eff22fd49d505","reportUrl":"https://status-im.github.io/status-cli-tests/176//#testresult/1e4eff22fd49d505","status":"passed","time":{"start":1724287325475,"stop":1724287373177,"duration":47702}},{"uid":"a5cd17c4a8b05f79","reportUrl":"https://status-im.github.io/status-cli-tests/175//#testresult/a5cd17c4a8b05f79","status":"failed","statusDetails":"AssertionError","time":{"start":1724257363388,"stop":1724257423077,"duration":59689}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"8aef3e67dba4be6c.json","parameterValues":[]}