{"uid":"bca2e6b45d7c548a","name":"test_fetch_community_with_packet_loss","fullName":"tests.test_fetch_community.TestFetchCommunity#test_fetch_community_with_packet_loss","historyId":"0eca0edbd90df8c1e44c54fb8592b7c8","time":{"start":1731630615549,"stop":1731630680252,"duration":64703},"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:13218 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=13218): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=13218): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:13218 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"set_allure_env_variables","time":{"start":1731629805861,"stop":1731629805861,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes","time":{"start":1731630607737,"stop":1731630607737,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"save_node_logs_on_fail","time":{"start":1731630607737,"stop":1731630607737,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"start_1_node","time":{"start":1731630607737,"stop":1731630615548,"duration":7811},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"RuntimeError: Request to http://127.0.0.1:13218 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","statusTrace":"/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:536: in _make_request\n    response = conn.getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connection.py:461: in getresponse\n    httplib_response = super().getresponse()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:1428: in getresponse\n    response.begin()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:331: in begin\n    version, status, reason = self._read_status()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/http/client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/socket.py:720: in readinto\n    return self._sock.recv_into(b)\nE   TimeoutError: timed out\n\nThe above exception was the direct cause of the following exception:\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:486: in send\n    resp = conn.urlopen(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:844: in urlopen\n    retries = retries.increment(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/util/util.py:39: in reraise\n    raise value\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:790: in urlopen\n    response = self._make_request(\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:538: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/urllib3/connectionpool.py:370: in _raise_timeout\n    raise ReadTimeoutError(\nE   urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=13218): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\nsrc/node/rpc_client.py:24: in send_rpc_request\n    response = requests.post(self.base_url, headers={\"Content-Type\": \"application/json\"}, data=json.dumps(payload), timeout=timeout)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:589: in request\n    resp = self.send(prep, **send_kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/sessions.py:703: in send\n    r = adapter.send(request, **kwargs)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/requests/adapters.py:532: in send\n    raise ReadTimeout(e, request=request)\nE   requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=13218): Read timed out. (read timeout=10)\n\nDuring handling of the above exception, another exception occurred:\ntests/test_fetch_community.py:38: in test_fetch_community_with_packet_loss\n    self.test_fetch_community_baseline()\ntests/test_fetch_community.py:18: in test_fetch_community_baseline\n    response = self.first_node.fetch_community(community_id)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/status_node.py:193: in fetch_community\n    return self.api.send_rpc_request(\"wakuext_fetchCommunity\", params, timeout=10)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:289: in wrapped_f\n    return self(f, *args, **kw)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:379: in __call__\n    do = self.iter(retry_state=retry_state)\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:325: in iter\n    raise retry_exc.reraise()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:158: in reraise\n    raise self.last_attempt.result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:449: in result\n    return self.__get_result()\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/concurrent/futures/_base.py:401: in __get_result\n    raise self._exception\n/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/tenacity/__init__.py:382: in __call__\n    result = fn(*args, **kwargs)\nsrc/node/rpc_client.py:33: in send_rpc_request\n    raise RuntimeError(error_message)\nE   RuntimeError: Request to http://127.0.0.1:13218 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","steps":[],"attachments":[{"uid":"c84d527693c60c6d","name":"log","source":"c84d527693c60c6d.txt","type":"text/plain","size":44617}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"save_node_logs_on_fail::0","time":{"start":1731630680490,"stop":1731630680492,"duration":2},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"clear_open_nodes::0","time":{"start":1731630680492,"stop":1731630680695,"duration":203},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"set_allure_env_variables::0","time":{"start":1731631397983,"stop":1731631397983,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"@pytest.mark.usefixtures('start_1_node')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_fetch_community"},{"name":"subSuite","value":"TestFetchCommunity"},{"name":"host","value":"fv-az1986-134"},{"name":"thread","value":"60975-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_fetch_community"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":19,"skipped":0,"passed":17,"unknown":0,"total":37},"items":[{"uid":"8663f9b7375687ee","reportUrl":"https://status-im.github.io/status-cli-tests/274//#testresult/8663f9b7375687ee","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:15426 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731544220024,"stop":1731544276373,"duration":56349}},{"uid":"2c838611be0228f3","reportUrl":"https://status-im.github.io/status-cli-tests/273//#testresult/2c838611be0228f3","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:35082 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731458074531,"stop":1731458132670,"duration":58139}},{"uid":"3e8d6f0f2d2eb0fe","reportUrl":"https://status-im.github.io/status-cli-tests/272//#testresult/3e8d6f0f2d2eb0fe","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:42872 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731371503072,"stop":1731371557571,"duration":54499}},{"uid":"95d72476163f7149","reportUrl":"https://status-im.github.io/status-cli-tests/271//#testresult/95d72476163f7149","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:15206 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731285241763,"stop":1731285305329,"duration":63566}},{"uid":"f9a2cf2229507596","reportUrl":"https://status-im.github.io/status-cli-tests/270//#testresult/f9a2cf2229507596","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:63984 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731198855053,"stop":1731198912624,"duration":57571}},{"uid":"a7fe08536ce15d60","reportUrl":"https://status-im.github.io/status-cli-tests/269//#testresult/a7fe08536ce15d60","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:26268 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1731112211826,"stop":1731112304505,"duration":92679}},{"uid":"f16d14dfa0ea597f","reportUrl":"https://status-im.github.io/status-cli-tests/268//#testresult/f16d14dfa0ea597f","status":"passed","time":{"start":1731025938256,"stop":1731026003809,"duration":65553}},{"uid":"257a8b60ef46765d","reportUrl":"https://status-im.github.io/status-cli-tests/267//#testresult/257a8b60ef46765d","status":"passed","time":{"start":1730939532943,"stop":1730939578338,"duration":45395}},{"uid":"490a302ecfcb4ab4","reportUrl":"https://status-im.github.io/status-cli-tests/266//#testresult/490a302ecfcb4ab4","status":"failed","statusDetails":"AssertionError: 1 community fetches out of 10: ,Community ID: 0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5, Error: 'NoneType' object is not subscriptable","time":{"start":1730853102930,"stop":1730853186079,"duration":83149}},{"uid":"ef33fb58f8ba04fb","reportUrl":"https://status-im.github.io/status-cli-tests/265//#testresult/ef33fb58f8ba04fb","status":"passed","time":{"start":1730766775270,"stop":1730766886903,"duration":111633}},{"uid":"830a402d4c9ba8a2","reportUrl":"https://status-im.github.io/status-cli-tests/264//#testresult/830a402d4c9ba8a2","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:3305 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730680273385,"stop":1730680333072,"duration":59687}},{"uid":"f01b88452cdc0313","reportUrl":"https://status-im.github.io/status-cli-tests/263//#testresult/f01b88452cdc0313","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:19276 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730594008661,"stop":1730594110159,"duration":101498}},{"uid":"772d237a32d69764","reportUrl":"https://status-im.github.io/status-cli-tests/262//#testresult/772d237a32d69764","status":"passed","time":{"start":1730507745998,"stop":1730507798024,"duration":52026}},{"uid":"38e54498913de9a8","reportUrl":"https://status-im.github.io/status-cli-tests/261//#testresult/38e54498913de9a8","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:2157 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730421226210,"stop":1730421288835,"duration":62625}},{"uid":"c4640186f31f769e","reportUrl":"https://status-im.github.io/status-cli-tests/260//#testresult/c4640186f31f769e","status":"passed","time":{"start":1730334744514,"stop":1730334829460,"duration":84946}},{"uid":"f77d086def7d3c61","reportUrl":"https://status-im.github.io/status-cli-tests/259//#testresult/f77d086def7d3c61","status":"passed","time":{"start":1730248292055,"stop":1730248358264,"duration":66209}},{"uid":"6211588dfcc6f817","reportUrl":"https://status-im.github.io/status-cli-tests/258//#testresult/6211588dfcc6f817","status":"broken","statusDetails":"RuntimeError: Request to http://127.0.0.1:49763 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node","time":{"start":1730161794239,"stop":1730161887020,"duration":92781}},{"uid":"5634d43112225a36","reportUrl":"https://status-im.github.io/status-cli-tests/257//#testresult/5634d43112225a36","status":"passed","time":{"start":1730075358443,"stop":1730075398697,"duration":40254}},{"uid":"9fb0657bb5e1929e","reportUrl":"https://status-im.github.io/status-cli-tests/256//#testresult/9fb0657bb5e1929e","status":"passed","time":{"start":1729989036955,"stop":1729989088956,"duration":52001}},{"uid":"1448d13594a322f6","reportUrl":"https://status-im.github.io/status-cli-tests/255//#testresult/1448d13594a322f6","status":"passed","time":{"start":1729902599275,"stop":1729902653491,"duration":54216}}]},"tags":["@pytest.mark.usefixtures('start_1_node')"]},"source":"bca2e6b45d7c548a.json","parameterValues":[]}